Repository tokyo-metropolitan-gov/covid19, pull requests merged in 2020-03, with the labels that each got.

#323 Add lang option
  components/SideNavigation.vue
Labels: Approved

#320 Update README
  README.md
Labels: Approved

#336 不要なファイルを削除
  components/Logo.vue
  components/VuetifyLogo.vue
  package.json
  static/v.png
  test/Logo.spec.js
Labels: Approved

#331 Add github actions status badge
  README.md
Labels: Approved

#368 pull request template を移動
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Merge Ready

#374 Doc: Update English section in README.md
  README.md
Labels: Merge Ready

#386 SideNavigation内の画像にaltを設定する
  components/SideNavigation.vue
Labels: Merge Ready

#406 fix: DataViewBasicInfoPanel の class 名
  components/DataTable.vue
  components/DataViewBasicInfoPanel.vue
Labels: Merge Ready

#410 【改善】既存のカラーコードを全て_variables.scssから取得するように修正
  components/DataView.vue
  components/NumberDisplay.vue
  components/PageHeader.vue
  components/SideNavigation.vue
  components/WhatsNew.vue
Labels: Merge Ready

#403 ローディング中の画像にaltを設定
  layouts/default.vue
Labels: Merge Ready

#388 chore: ファイル構造の整理とパブリックに表示されるべきではないファイルの削除
  middleware/README.md
  static/README.md
  store/README.md
  types/svg-shim.d.ts
  types/vue-shim.d.ts
Labels: 改善提案

#381 Git ステージ時の ESLint の発火対象の拡大(.ts, .vue サポート)
  .eslintignore
  package.json
Labels: 改善提案

#382 chore: VSCode 向けのエディタ設定の追加
  .eslintrc
  .vscode/settings.json
Labels: 改善提案

#359 （棒グラフ共通）右上に表示する数値の変更
  components/DataView.vue
  components/DataViewBasicInfoPanel.vue
  components/TimeBarChart.vue
Labels: IMPORTANT

#367 開発用の Docker Compose 設定を追加
  .dockerignore
  Dockerfile
  README.md
  docker-compose.yml
  nuxt.config.js
Labels: 改善提案

#422 コピーライトの表記を (C) ではなく © とする
  components/SideNavigation.vue
Labels: waiting

#416 Tools: tool/convert.php で生成される日付文字列形式を慣習的なものに
  tool/convert.php
Labels: Merge Ready

#417 nuxt-i18nのformatFallbackMessages設定を修正
  nuxt.config.js
Labels: IMPORTANT

#413 feat: 正しい lang 属性を html タグに付与
  layouts/default.vue
Labels: IMPORTANT

#354 feat: お知らせの複数表示への対応
  components/WhatsNew.vue
  data/news.json
  pages/index.vue
Labels: waiting

#475 chore: Issue Template の分割(再)
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/IMPROVE_SUGGESTIONS.md
Labels: improve

#510 検査実施日別状況のタイトルと単位を修正
  components/TimeStackedBarChart.vue
  pages/index.vue
Labels: Merge Ready

#472 fix: 都営地下鉄の利用者数グラフの縦軸の数値を読みやすくする
  pages/index.vue
Labels: Merge Ready

#511 外部リンクに rel="noopener" を追加
  components/DataView.vue
  components/WhatsNew.vue
Labels: Merge Ready

#541 fix: canonical が消えていたのを修正
  layouts/default.vue
Labels: Merge Ready

#587 tool/convert.php を tool ディレクトリ以外からでも実行できるよう修正
  tool/convert.php
Labels: Merge Ready

#578 htmlのlangタグをBCP準拠に変更
  nuxt.config.js
Labels: Merge Ready

#572 Dockerfile の修正
  Dockerfile
  README.md
  docker-compose.yml
Labels: Merge Ready

#562 不要なconstants.jsの削除
  constants.js
  pull_datasource.sh
Labels: Merge Ready

#549 GitHub のレポジトリ トップ画像をクリックすると本番サイトへリンクするよう変更
  README.md
Labels: Merge Ready

#532 chore: Fix issue template style
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/IMPROVE_SUGGESTIONS.md
Labels: Merge Ready

#526 chore: Raise the minimum version of nuxt to 2.9.0
  package.json
  yarn.lock
Labels: Merge Ready

#496 画像容量を圧縮
  static/apple-touch-icon-precomposed.png
  static/confirmed-cases-table.svg
  static/covid.svg
  static/flow.png
  static/flow/sp/sp_flow_01_01@2x.png
  static/flow/sp/sp_flow_01_02@2x.png
  static/flow/sp/sp_flow_01_02_03_nav@2x.png
  static/flow/sp/sp_flow_02@2x.png
  static/flow/sp/sp_flow_03@2x.png
  static/flow/sp/sp_flow_04@2x.png
  static/flow/sp/sp_flow_04_nav@2x.png
  static/flow/sp/sp_flow_05_bg@2x.png
  static/flow/sp/sp_flow_06@2x.png
  static/flow/sp/sp_flow_06_01@2x.png
  static/flow/sp/sp_flow_06_02@2x.png
  static/flow/sp/sp_flow_06_03@2x.png
  static/flow/sp/sp_flow_06_nav_01@2x.png
  static/flow/sp/sp_flow_06_nav_02@2x.png
  static/flow/sp/sp_flow_06_nav_03@2x.png
  static/flow/sp/sp_flow_06_nav_04@2x.png
  static/flow/sp/sp_flow_tel_01@2x.png
  static/flow/sp/sp_flow_tel_03@2x.png
  static/flow_sp.png
  static/line.png
  static/logo.svg
  static/parent.svg
  static/twitter.png
Labels: Merge Ready

#577 Node.js のバージョンを README に明記する
  .node-version
  README.md
  package.json
Labels: Merge Ready

#617 lintエラーでビルドが失敗していたので文言のフォーマット
  pages/worker.vue
Labels: hotfix

#607 covid がVSCodeでスペルミス扱いにならないようにする
  .vscode/cspell.json
Labels: Merge Ready

#627 Typo?
  pages/flow.vue
Labels: Merge Ready

#626 dockerignoreの追記
  .dockerignore
Labels: Merge Ready

#625 refactor: Setup Nuxt.js and TypeScript environment
  layouts/default.vue
  layouts/error.vue
  nuxt.config.ts
  package.json
  plugins/README.md
  plugins/vue-chart.js
  plugins/vue-chart.ts
  tsconfig.json
  types/shims-sfc.d.ts
  types/shims-vue.d.ts
  yarn.lock
Labels: Merge Ready, refactoring

#494 fix: グラフで表示される数値をカンマ区切りに修正
  components/TimeBarChart.vue
  components/TimeStackedBarChart.vue
Labels: Merge Ready

#650 ESLintのエラーをコメントしてくれるGitHub Actionsの追加
  .github/workflows/reviewdog.yml
Labels: improve

#369 Twitter Card の追加
  nuxt.config.ts
Labels: waiting

#495 積み上げ棒グラフのツールチップに合計値を表示
  components/TimeStackedBarChart.vue
Labels: improve, ui improve

#542 #528: 「最新のお知らせ」に外部リンクアイコンを追加
  components/WhatsNew.vue
Labels: duplicate

#497 グラフ。月の表示を日付から切り離すように調整。
  components/TimeBarChart.vue
  components/TimeStackedBarChart.vue
Labels: improve, ui improve

#701 [i18n] (PR)SideNavigation.vue 内の文字列をi18n化
  components/SideNavigation.vue
Labels: Merge Ready, i18n

#706 [i18n] DataSelector.vue 内の文字列をi18n化
  components/DataSelector.vue
Labels: i18n

#817 [i18n] DataView.vue 内の文字列をi18n化
  .github/CONTRIBUTING.md
  .github/CONTRIBUTING_EN.md
  CONTRIBUTORS.md
  components/DataView.vue
  components/MetroBarChart.vue
  components/SvgCard.vue
  components/TimeStackedBarChart.vue
Labels: Merge Ready, i18n

#735 [i18n] parent.vue 内の文字列をi18n化
  pages/parent.vue
Labels: Merge Ready, i18n

#719 [i18n] WhatsNew.vue 内の文字列をi18n化
  components/WhatsNew.vue
Labels: Merge Ready, i18n

#827 Fix language selector label for zh-TW (体 -> 體)
  nuxt.config.ts
Labels: Merge Ready, i18n

#404 fix: 新型コロナウイルス感染症が心配なときにの詳細リンク先の修正
  pages/flow.vue
Labels: waiting

#830 [i18n] error.vue 内の文字列をi18n化
  layouts/error.vue
Labels: Merge Ready, i18n

#727 [i18n] (PR)index.vue 内の文字列をi18n化
  pages/index.vue
Labels: Merge Ready, i18n, improve

#842 [i18n] SvgCard.vue 内の文字列をi18n化
  components/SvgCard.vue
Labels: Merge Ready, i18n

#826 [i18n]TimeBarChart.vue内の文字列をi18n化
  components/TimeBarChart.vue
Labels: Merge Ready, i18n

#438 サイドバーにFacebookアカウントへのリンク（アイコン）を追加
  components/SideNavigation.vue
  static/facebook.png
Labels: waiting

#818 カード背景色の修正 #808
  pages/flow.vue
Labels: Merge Ready

#784 URLの末尾に "/" が付くケースでもサイドバーのアイテムを Active にする
  components/ListItem.vue
Labels: Merge Ready

#871 [i18n] (PR)「陽性患者の属性」テーブルの翻訳
  pages/index.vue
Labels: Merge Ready, i18n

#863 [i18n] TimeBarChartグラフの小さな修正
  components/TimeBarChart.vue
Labels: Merge Ready, i18n

#873 [i18n] components, pages 以下の vue ファイルの辞書を更新
  components/SideNavigation.vue
  components/SvgCard.vue
  pages/index.vue
  pages/parent.vue
Labels: Merge Ready, i18n

#882 feat(docs) README, COD, CONTRIBUTING 韓国語翻訳
  .github/CODE_OF_CONDUCT_KO.md
  .github/CONTRIBUTING_KO.md
  README.md
  README_EN.md
  README_ES.md
  README_KO.md
Labels: documentation, i18n

#828 [i18n] about.vue 内の文字列をi18n化
  pages/about.vue
Labels: Merge Ready, i18n

#717 [i18n] MetroBarChart.vue 内の文字列をi18n化
  components/MetroBarChart.vue
Labels: Merge Ready, i18n

#622 陽性患者属性テーブルに退院列を追加
  components/DataTable.vue
  utils/formatTable.ts
Labels: waiting

#718 [i18n] PageHeader.vue 内の文字列をi18n化
  components/PageHeader.vue
Labels: i18n, waiting

#907 [i18n] about.vue 内のリンク付き文字列をi18n化
  pages/about.vue
Labels: Merge Ready, i18n

#927 [i18n] サイドバーの外部リンクに「日本語のみ」を追加
  components/SideNavigation.vue
Labels: Merge Ready, i18n

#732 [i18n] worker.vue 内の文字列をi18n化
  pages/worker.vue
Labels: i18n, waiting

#955 [i18n] pages/flow.vue のi18n化
  pages/flow.vue
Labels: i18n

#755 TextCard コンポーネントで slot や body プロパティを受け取る要素を div に変更した
  components/TextCard.vue
Labels: Merge Ready, accessibility

#989 [i18n] components/flow/FlowPcRequired.vue のi18n化
  components/flow/FlowPcRequired.vue
Labels: Merge Ready, i18n

#960 [i18n] components/flow/FlowPcNotRequired.vue のi18n化
  components/flow/FlowPcNotRequired.vue
Labels: Merge Ready, i18n

#980 [i18n] components/flow/FlowPcPcr.vue のi18n化
  components/flow/FlowPcPcr.vue
Labels: Merge Ready, i18n

#981 issue-768: コンポーネント内の見出しレベルを h3 に変更した
  components/TextCard.vue
Labels: Merge Ready, accessibility

#992 [i18n] components/flow/FlowPcSuspect.vue のi18n化
  components/flow/FlowPcSuspect.vue
Labels: Merge Ready, i18n

#1000 [i18n] fallback翻訳が効かない部分に0を指定(一時的措置)
  components/flow/FlowPcNotRequired.vue
Labels: Merge Ready, i18n

#1021 [i18n] 陽性患者の属性テーブルの翻訳の改善・更新
  components/DataTable.vue
  pages/index.vue
Labels: Merge Ready, i18n

#1023 [i18n] components/flow/FlowSp.vue のi18n化
  components/flow/FlowSp.vue
Labels: Merge Ready, i18n

#1031 [i18n] components/flow/FlowSpAccording.vue のi18n化
  components/flow/FlowSpAccording.vue
Labels: Merge Ready, i18n

#1043 [/flow] 不要な eslint-disable を除去
  components/flow/FlowPcSuspect.vue
Labels: Merge Ready

#1038 [i18n] components/flow/FlowSpAdvisory.vue のi18n化
  components/flow/FlowSpAdvisory.vue
Labels: Merge Ready, i18n

#1048 [i18n] components/flow/FlowSpElder.vue のi18n化
  components/flow/FlowSpElder.vue
Labels: Merge Ready, i18n

#1049 [i18n] components/flow/FlowSpGeneral.vue のi18n化
  components/flow/FlowSpGeneral.vue
Labels: Merge Ready, i18n

#1054 [i18n] components/flow/FlowSpPast.vue のi18n化
  components/flow/FlowSpPast.vue
Labels: Merge Ready, i18n

#1056 [i18n] components/flow/FlowSpSuspect.vue のi18n化
  components/flow/FlowSpSuspect.vue
Labels: Merge Ready, i18n

#861 [i18n]TimeStackedBarChart.vue 内の文字列をi18n化
  components/TimeStackedBarChart.vue
Labels: Merge Ready, i18n

#1066 [/flow][i18n] コンポーネントリファクタリング FlowPcPcr.vue
  components/flow/FlowPcPcr.vue
Labels: Merge Ready, i18n

#1029 [/flow][i18n] コンポーネントリファクタリング FlowPcHospitalized.vue
  components/flow/FlowPcHospitalized.vue
Labels: Merge Ready, i18n

#1068 [/flow][i18n] コンポーネントリファクタリング FlowSpElder.vue
  components/flow/FlowSpElder.vue
Labels: Merge Ready, i18n

#1112 [/flow][i18n] FlowPcDays.vue マークアップ修正
  components/flow/FlowPcDays.vue
Labels: Merge Ready, i18n

#1116 [i18n] FlowPc.vue 翻訳調整
  components/flow/FlowPc.vue
Labels: Merge Ready, i18n

#1107 [i18n] (PR)ConfirmedCasesTable.vue 内の文字列をi18n化
  components/ConfirmedCasesTable.vue
Labels: Merge Ready, i18n

#1108 [i18n] TimeStackedBarChart.vue の翻訳の改善・更新
  components/TimeStackedBarChart.vue
Labels: Merge Ready, i18n

#961 [WIP] [i18n] components/flow/FlowPcPast.vue のi18n化
  components/flow/FlowPcPast.vue
Labels: Merge Ready, i18n

#854 [i18n] 言語切り替えメニューを追加
  components/LanguageSelector.vue
  components/SideNavigation.vue
  pages/about.vue
  pages/flow.vue
  pages/index.vue
  pages/parent.vue
  pages/worker.vue
  static/earth.svg
  static/selectmenu.svg
Labels: Assigned, i18n

#1119 [i18n] components/flow/FlowPcDays.vue i18n化残りの分
  components/flow/FlowPcDays.vue
Labels: Merge Ready, i18n

#1060 [i18n] PrinterButton.vue 内の文字列の翻訳を更新
  components/PrinterButton.vue
Labels: Merge Ready, i18n

#1050 feat: 入庁者の推移グラフを追加
  components/AgencyBarChart.vue
  data/agency.json
  pages/index.vue
Labels: waiting

#822 多言語対応対応
  CONTRIBUTORS.md
  assets/global.scss
  assets/variables.scss
  components/ConfirmedCasesTable.vue
  components/DataSelector.vue
  components/DataTable.vue
  components/DataView.vue
  components/LanguageSelector.vue
  components/MetroBarChart.vue
  components/PageHeader.vue
  components/PrinterButton.vue
  components/SideNavigation.vue
  components/SvgCard.vue
  components/TextCard.vue
  components/TimeBarChart.vue
  components/TimeStackedBarChart.vue
  components/WhatsNew.vue
  components/flow/.gitkeep
  components/flow/FlowPc.vue
  components/flow/FlowPcAdvisory.vue
  components/flow/FlowPcDays.vue
  components/flow/FlowPcHospitalized.vue
  components/flow/FlowPcNotRequired.vue
  components/flow/FlowPcPast.vue
  components/flow/FlowPcPcr.vue
  components/flow/FlowPcRequired.vue
  components/flow/FlowPcSuspect.vue
  components/flow/FlowSp.vue
  components/flow/FlowSpAccording.vue
  components/flow/FlowSpAdvisory.vue
  components/flow/FlowSpElder.vue
  components/flow/FlowSpGeneral.vue
  components/flow/FlowSpHospitalized.vue
  components/flow/FlowSpPast.vue
  components/flow/FlowSpSuspect.vue
  layouts/error.vue
  nuxt.config.ts
  pages/about.vue
  pages/flow.vue
  pages/index.vue
  pages/parent.vue
  pages/worker.vue
  static/earth.svg
  static/flow/arrow_downward.svg
  static/flow/arrow_green.svg
  static/selectmenu.svg
  tsconfig.json
Labels: i18n

#1139 update data of 0311
  data/agency.json
  data/data.json
  static/data/130001_tokyo_covid19_patients.csv
Labels: Merge Ready

#1143 都庁来庁者数の推移 のi18n化
  components/AgencyBarChart.vue
  pages/index.vue
Labels: i18n

#1160 [i18n] components/flow/FlowSpAdvisory.vue のi18n化
  components/flow/FlowSpAdvisory.vue
Labels: Merge Ready, i18n

#1162 [i18n] スマホ版flowページの翻訳を無効化
  components/flow/FlowSp.vue
  components/flow/FlowSpAccording.vue
  components/flow/FlowSpAdvisory.vue
  components/flow/FlowSpElder.vue
  components/flow/FlowSpGeneral.vue
  components/flow/FlowSpPast.vue
  components/flow/FlowSpSuspect.vue
Labels: Merge Ready, i18n

#1094 Update English wording
  components/SideNavigation.vue
  pages/index.vue
Labels: Merge Ready, i18n

#1151 [i18n] fix: 英語表記のグラフで文字が重ならないように修正
  components/DataSelector.vue
  components/DataView.vue
  components/DataViewBasicInfoPanel.vue
  components/TimeStackedBarChart.vue
Labels: Merge Ready

#1166 [i18n] FlowPcRequired.vue 内の翻訳を更新
  components/flow/FlowPcRequired.vue
Labels: Merge Ready, i18n

#1191 [i18n] スマホ版flowページのi18n復活
  components/flow/FlowSp.vue
  components/flow/FlowSpAccording.vue
  components/flow/FlowSpAdvisory.vue
  components/flow/FlowSpElder.vue
  components/flow/FlowSpGeneral.vue
  components/flow/FlowSpPast.vue
  components/flow/FlowSpSuspect.vue
Labels: Merge Ready, i18n

#1200 お問い合わせ先デグレを修正（hotfix）
  pages/about.vue
Labels: Merge Ready

#1202 お問い合わせ先デグレを修正 (into development branch)
  components/LanguageSelector.vue
  pages/about.vue
Labels: Merge Ready

#1194 aboutページのgithubリンク修正
  pages/about.vue
Labels: Merge Ready

#1211 [i18n] components/flow/FlowSpAccording.vue i18n化残りの分
  components/flow/FlowSpAccording.vue
Labels: Merge Ready, i18n

#1215 [i18n] components/flow/FlowSpElder.vue i18n化残りの分
  components/flow/FlowSpElder.vue
Labels: Merge Ready, i18n

#1218 [i18n] components/flow/FlowSpElder.vue i18n化残りの分
  components/flow/FlowSpPast.vue
Labels: Merge Ready, i18n

#1219 [i18n] components/flow/FlowSpHospitalized.vue のi18n化
  components/flow/FlowSpHospitalized.vue
Labels: Merge Ready, i18n

#1226 [i18n] 「やさしい日本語」言語設定を復活
  nuxt.config.ts
Labels: i18n

#1230 [/flow] [i18n] (PR) SP英語版で「n日程度続いている」の日数部分が表示されていない
  components/flow/FlowSpElder.vue
  components/flow/FlowSpGeneral.vue
Labels: i18n

#1237 [i18n] PC版検査の必要あり/なし の翻訳キーをスマホ版に統一
  components/flow/FlowPcRequired.vue
Labels: Merge Ready, i18n

#1164 グラフの凡例がクリッカブルであることを示すよう、cursor: pointerを指定
  components/AgencyBarChart.vue
  components/TimeStackedBarChart.vue
  pages/index.vue
Labels: Merge Ready

#835 各グラフデータ毎にOGPカード、パーマリンクを設ける
  .eslintignore
  .github/workflows/ogp_builder.yml
  .gitignore
  components/DataView.vue
  components/cards/AgencyCard.vue
  components/cards/ConfirmedCasesAttributesCard.vue
  components/cards/ConfirmedCasesDetailsCard.vue
  components/cards/ConfirmedCasesNumberCard.vue
  components/cards/ConsultationDeskReportsNumberCard.vue
  components/cards/MetroCard.vue
  components/cards/TelephoneAdvisoryReportsNumberCard.vue
  components/cards/TestedNumberCard.vue
  layouts/default.vue
  nuxt.config.ts
  package.json
  pages/cards/_card.vue
  pages/index.vue
  static/ogp-attributes-of-confirmed-cases.png
  static/ogp-details-of-confirmed-cases.png
  static/ogp-number-of-confirmed-cases.png
  static/ogp-number-of-reports-to-covid19-consultation-desk.png
  static/ogp-number-of-reports-to-covid19-telephone-advisory-center.png
  static/ogp-number-of-tested.png
  static/ogp-predicted-number-of-toei-subway-passengers.png
  ui-test/ogp_screenshot.py
  yarn.lock
Labels: waiting

#1282 トップページの一部翻訳漏れを修正
  components/AgencyBarChart.vue
  components/cards/AgencyCard.vue
  components/cards/ConfirmedCasesNumberCard.vue
Labels: i18n

#730 「陽性患者の属性」の「日付」を「公表日」に変える
  utils/formatTable.ts
Labels: Merge Ready

#1274 [i18n] 言語切り替えメニューのリファクタリング
  components/LanguageSelector.vue
Labels: i18n

#1240 ページ内のランドマークを改善しスクリーンリーダーのアクセシビリティを向上する
  components/DataView.vue
  components/SideNavigation.vue
  layouts/default.vue
Labels: Merge Ready, accessibility

#1285 Fix the English translation of 「入院」
  components/flow/FlowPcHospitalized.vue
  components/flow/FlowSpHospitalized.vue
Labels: i18n

#1308 翻訳の反映漏れを修正
  components/flow/FlowPc.i18n.json
  components/flow/FlowPcHospitalized.i18n.json
Labels: i18n

#1286 翻訳シートの反映漏れを直接変更
  components/MetroBarChart.vue
Labels: i18n

#1311 [i18n] 翻訳チェック・更新のために dev-i18n を更新
  .github/CODE_OF_CONDUCT_ZH_TW.md
  .github/CONTRIBUTING.md
  .github/CONTRIBUTING_ZH_TW.md
  README.md
  README_EN.md
  README_ES.md
  README_KO.md
  README_VI.md
  README_ZH_CN.md
  README_ZH_TW.md
  components/DataView.vue
  components/NoScript.vue
  components/SideNavigation.vue
  forkedSites.md
  layouts/default.vue
  static/line.png
  static/twitter.png
Labels: i18n

#1327 「東京都主催等 中止又は延期するイベント等」のリンク先を変更
  components/SideNavigation.vue
Labels: Merge Ready

#1062 TypeScriptのドキュメンテーション環境を整備
  .eslintrc
  package.json
  utils/formatConfirmedCases.ts
  utils/formatDate.ts
  utils/formatGraph.ts
  utils/formatTable.ts
Labels: Merge Ready

#1360 「専門的な助言が必要な場合」の上部の矢印は上向きが正
  components/flow/FlowPc.vue
Labels: Merge Ready

#1328 [WIP] Dev-a11y-flow を development に取り込む
  components/flow/FlowSpAccording.vue
  components/flow/FlowSpAdvisory.vue
  components/flow/FlowSpElder.vue
  components/flow/FlowSpGeneral.vue
  components/flow/FlowSpHospitalized.vue
  components/flow/FlowSpPast.vue
  components/flow/FlowSpSuspect.vue
  components/flow/flow_sp.scss
  static/flow/responsive/accessibility.svg
  static/flow/responsive/accessible.svg
  static/flow/responsive/apartment.svg
  static/flow/responsive/arrow_downward.svg
  static/flow/responsive/arrow_forward.svg
  static/flow/responsive/arrow_green.svg
  static/flow/responsive/check_circle.svg
  static/flow/responsive/directions_walk.svg
  static/flow/responsive/flow_arrow.svg
  static/flow/responsive/hotel.svg
  static/flow/responsive/house.svg
  static/flow/responsive/phone.svg
  static/flow/responsive/pregnant_woman.svg
  static/flow/responsive/sentiment_very_dissatisfied.svg
Labels: Merge Ready

#1320 [i18n] pages/flow.i18n.json, pages/flow.vue の更新
  pages/flow.i18n.json
  pages/flow.vue
Labels: Merge Ready, i18n

#1337 [i18n] components/AgencyBarChart.i18n.json の更新
  components/AgencyBarChart.i18n.json
Labels: Merge Ready, i18n

#1353 [i18n] components/ConfirmedCaseTable.i18n.json の更新
  components/ConfirmedCasesTable.i18n.json
Labels: Merge Ready, i18n

#1358 [i18n] AgencyCardの言語設定更新（ファイル分割、翻訳反映） ISSUE #1312
  components/cards/AgencyCard.i18n.json
  components/cards/AgencyCard.vue
Labels: Merge Ready, i18n

#1387 [i18n] components/PageHeader.i18n.json の更新
  components/PageHeader.i18n.json
Labels: Merge Ready, i18n

#1388 [i18n] components/PrinterButton.i18n.json の翻訳を更新
  components/PrinterButton.i18n.json
Labels: Merge Ready, i18n

#1403 [i18n] components/WhatsNew.i18n.json のチェック・更新
  components/WhatsNew.i18n.json
Labels: Merge Ready, i18n

#1402 [i18n] components/SideNavigation.i18n.json のチェック・更新
  components/SideNavigation.i18n.json
Labels: Merge Ready, i18n

#1392 [WIP][i18n][/flow][Pc] components/flow/FlowPcXxxx.i18n.json を更新
  components/flow/FlowPc.i18n.json
  components/flow/FlowPcAdvisory.i18n.json
  components/flow/FlowPcDays.i18n.json
  components/flow/FlowPcHospitalized.i18n.json
  components/flow/FlowPcNotRequired.i18n.json
  components/flow/FlowPcPast.i18n.json
  components/flow/FlowPcPcr.i18n.json
  components/flow/FlowPcRequired.i18n.json
  components/flow/FlowPcSuspect.i18n.json
  components/flow/FlowSp.i18n.json
  components/flow/FlowSpAccording.i18n.json
  components/flow/FlowSpAdvisory.i18n.json
  components/flow/FlowSpAdvisory.vue
  components/flow/FlowSpElder.i18n.json
  components/flow/FlowSpGeneral.i18n.json
  components/flow/FlowSpPast.i18n.json
  components/flow/FlowSpSuspect.i18n.json
Labels: Merge Ready, i18n

#1393 山梨県版のリンクをforkedSites.mdに追加
  forkedSites.md
Labels: Merge Ready

#1330 ForkedSite.mdに岐阜県を追加
  forkedSites.md
Labels: Merge Ready

#1428 [i18n][/flow][Sp] components/flow/FlowSpXxxx.i18n.json を更新
  components/cards/ConsultationDeskReportsNumberCard.vue
  components/flow/FlowPcAdvisory.i18n.json
  components/flow/FlowPcAdvisory.vue
  components/flow/FlowPcNotRequired.i18n.json
  components/flow/FlowPcNotRequired.vue
  components/flow/FlowSpAccording.i18n.json
  components/flow/FlowSpAccording.vue
  components/flow/FlowSpAdvisory.i18n.json
  components/flow/FlowSpAdvisory.vue
  components/flow/FlowSpElder.i18n.json
  components/flow/FlowSpGeneral.i18n.json
  components/flow/FlowSpHospitalized.i18n.json
  components/flow/FlowSpPast.i18n.json
  components/flow/FlowSpSuspect.i18n.json
Labels: Merge Ready, i18n

#1345 [i18n] pages/index.i18n.json の更新 やさしい日本語対応
  pages/index.i18n.json
Labels: Merge Ready, i18n

#1447 [i18n] components/DataTable.i18n.json のチェック・更新 2
  components/DataTable.i18n.json
Labels: Merge Ready, i18n

#1448 [i18n] components/MetroBarChart.i18n.json のチェック・更新 2
  components/MetroBarChart.i18n.json
Labels: Merge Ready, i18n

#1449 [i18n] components/SvgCard.i18n.json のチェック・更新 2
  components/SvgCard.i18n.json
Labels: Merge Ready, i18n

#1450 [i18n] components/TimeBarChart.i18n.json のチェック・更新 2
  components/TimeBarChart.i18n.json
Labels: Merge Ready, i18n
