Repository tokyo-metropolitan-gov/covid19, pull requests merged in 2020-08, with the labels that each got.

#5156 Update CONTRIBUTING.md
  docs/zh_TW/CONTRIBUTING.md
Labels: ready-for-merge

#5170 FORKED_SITES.mdに富山県版サイトを追加
  FORKED_SITES.md
Labels: ready-for-merge

#5168 CONTRIBUTORS.md の更新 (2020-08-02)
  CONTRIBUTORS.md
Labels: ready-for-merge

#5158 getComplementedDateの戻り値をハイフン区切りの文字列に修正
  components/TimeBarChart.vue
  components/TimeStackedBarChart.vue
  components/cards/AgencyCard.vue
  components/cards/MetroCard.vue
  package.json
  utils/formatDate.ts
  yarn.lock
Labels: ready-for-merge

#5178 グラフのY軸のずれを修正（labelsの「2020/1/1」をハイフン区切りに）
  components/ConfirmedCasesIncreaseRatioByWeekChart.vue
  components/DashedRectangleTimeBarChart.vue
  components/MixedBarAndLineChart.vue
  components/MonitoringConfirmedCasesChart.vue
  components/MonitoringConsultationDeskReportChart.vue
  components/PositiveRateMixedChart.vue
  components/SevereCaseBarChart.vue
  components/TimeBarChart.vue
  components/TimeStackedBarChart.vue
  components/UntrackedRateMixedChart.vue
Labels: ready-for-merge

#5181 IE11向けに日付フォーマットを調整
  components/DashedRectangleTimeBarChart.vue
  components/SevereCaseBarChart.vue
  components/TimeBarChart.vue
  components/TimeStackedBarChart.vue
  components/cards/HospitalizedNumberCard.vue
  components/cards/SevereCaseCard.vue
  components/cards/TestedNumberCard.vue
  utils/formatGraph.ts
Labels: ready-for-merge

#5063 flow.vue: スクロール時にアイコンを非表示化
  pages/flow.vue
Labels: officially-approved, ready-for-merge

#5195 Fix hard coded japanese string literals
  components/MonitoringCommentCard.vue
  components/cards/UntrackedRateCard.vue
Labels: ready-for-merge

#5183 モニタリング項目(3)グラフとY軸のスケールが一致していないのを修正・Y軸を左右逆に
  components/UntrackedRateMixedChart.vue
Labels: officially-approved, ready-for-merge

#5239 components/DataSelector.vue の余分なTODO コメントを削除
  components/DataSelector.vue
Labels: ready-for-merge

#5236 for文/Array.forEach()を削減 (components/UntrackedRateMixedChart.vue)
  components/UntrackedRateMixedChart.vue
Labels: ready-for-merge

#5235 for文/Array.forEach()を削減 (components/cards/TestedNumberCard.vue)
  components/cards/TestedNumberCard.vue
Labels: ready-for-merge

#5234 for文/Array.forEach()を削減 (components/cards/PositiveRateCard.vue)
  components/cards/PositiveRateCard.vue
Labels: ready-for-merge

#5233 for文/Array.forEach()を削減 (components/PositiveRateMixedChart.vue)
  components/PositiveRateMixedChart.vue
Labels: ready-for-merge

#5231 for文/Array.forEach()を削減 (components/TimeStackedBarChart.vue)
  components/TimeStackedBarChart.vue
Labels: ready-for-merge

#5230 for文/Array.forEach()を削減 (components/cards/ConfirmedCasesByMunicipalitiesCard.vue)
  components/cards/ConfirmedCasesByMunicipalitiesCard.vue
Labels: ready-for-merge

#5229 for文/Array.forEach()を削減 (components/cards/ConsultationAboutFeverNumberCard.vue)
  components/cards/ConsultationAboutFeverNumberCard.vue
Labels: ready-for-merge

#5228 for文/Array.forEach()を削減 (components/cards/HospitalizedNumberCard.vue)
  components/cards/HospitalizedNumberCard.vue
Labels: ready-for-merge

#5227 for文/Array.forEach()を削減 (components/cards/SevereCaseCard.vue)
  components/cards/SevereCaseCard.vue
Labels: ready-for-merge

#5226 for文/Array.forEach()を削減 (components/cards/TokyoRulesApplicationNumberCard.vue)
  components/cards/TokyoRulesApplicationNumberCard.vue
Labels: ready-for-merge

#5225 for文/Array.forEach()を削減 (components/cards/UntrackedRateCard.vue)
  components/cards/UntrackedRateCard.vue
Labels: ready-for-merge

#5224 for文/Array.forEach()を削減 (nuxt.config.ts)
  nuxt.config.ts
Labels: ready-for-merge

#5222 for文/Array.forEach()を削減 (utils/formatTable.ts)
  utils/formatTable.ts
Labels: ready-for-merge

#5216 Reviewdog が適切に動作しない問題を修正
  .github/workflows/reviewdog.yml
  components/cards/AgencyCard.vue
  components/cards/MetroCard.vue
  utils/i18nUtils.ts
Labels: ready-for-merge

#5213 発症日別による陽性者数の推移グラフの追加
  components/CardsReference.vue
  components/DataView.vue
  components/DataViewCustomInfoPanel.vue
  components/TimeBarChart.vue
  components/cards/PositiveNumberByDevelopedDateCard.vue
  nuxt.config.ts
  pages/cards/_card.vue
  ui-test/ogp_screenshot.py
Labels: officially-approved, ready-for-merge

#5212 nuxt-i18n.config.ts の`as any`を削除
  nuxt-i18n.config.ts
Labels: ready-for-merge

#5210 「新規患者に関する報告件数の推移」グラフタイトル修正・リンクボタン追加
  components/CardsMonitoring.vue
  components/cards/ConfirmedCasesNumberCard.vue
Labels: officially-approved, ready-for-merge

#5089 モニタリング項目のマークアップをtableからlistに修正
  assets/monitoringItemsTableCommon.scss
  components/MonitoringItemsOverviewTableInfectionStatus.vue
  components/MonitoringItemsOverviewTableMedicalSystem.vue
  components/MonitoringItemsOverviewTableValueWithTranslatableUnit.vue
Labels: officially-approved, ready-for-merge

#5205 確定日別による陽性者数の推移グラフ注釈の修正
  components/cards/PositiveNumberByDiagnosedDateCard.vue
Labels: officially-approved, ready-for-merge

#5206 「陽性者」への用語の統一
  components/CardsReference.vue
  components/ConfirmedCasesByMunicipalitiesTable.vue
  components/cards/ConfirmedCasesAttributesCard.vue
  components/cards/ConfirmedCasesByMunicipalitiesCard.vue
Labels: officially-approved, ready-for-merge

#5248 使用されていないファイルを削除する
  components/SourceLink.vue
  data/13101_daily_visitors.json
  data/13104_daily_visitors.json
  data/test.json
  dist/data/.gitkeep
  dist/data/130001_tokyo_covid19_call_center.csv
  dist/data/130001_tokyo_covid19_combined_telephone_advice_center.csv
  dist/data/130001_tokyo_covid19_patients.csv
  static/.well-known/pki-validation/06c9242ba3a94dc1e48d8ea4ad24b59c.txt
  static/confirmed-cases-table.svg
  static/data/13104.csv
  utils/formatMonitoringStatus.ts
Labels: ready-for-merge

#5258 fix #5204 「カードによって注釈の字下げスタイルの揺れがある」修正
  components/cards/HospitalizedNumberCard.vue
  components/cards/MonitoringConfirmedCasesNumberCard.vue
  components/cards/SevereCaseCard.vue
Labels: ready-for-merge

#5260 "「＃7119」" の太字化・カギカッコ除去
  components/cards/MonitoringItemsOverviewCard.vue
Labels: i18n, need-i18n, ready-for-merge

#5263 全角ハイフンマイナスを翻訳対象外にする
  auto-i18n/i18n_generator.py
  components/cards/ConfirmedCasesAttributesCard.vue
Labels: ready-for-merge

#5264 npm scriptsから lint-and-generate を削除
  package.json
Labels: ready-for-merge

#5109 Feature: indicate JST timezone for when the page was last updated
  components/SiteTopUpper.vue
  docs/en/FOR_DEVELOPERS.md
  utils/formatDate.ts
Labels: i18n, ready-for-merge

#5280 「都内の最新感染動向」ページ内の外部リンクに外部リンクであることを示すアイコンを追加
  components/MonitoringCommentCard.vue
Labels: ready-for-merge

#5275 Fix #5208 ツールチップに日付表記の揺れがある
  components/DashedRectangleTimeBarChart.vue
  components/MixedBarAndLineChart.vue
  components/MonitoringConfirmedCasesChart.vue
  components/MonitoringConsultationDeskReportChart.vue
  components/SevereCaseBarChart.vue
  components/UntrackedRateMixedChart.vue
Labels: ready-for-merge

#5270 「企業の皆様・はたらく皆様へ」ページの一部コンテンツ差し替え（「東京都感染拡大防止協力金（第2回）」→「東京都家賃等支援給付金」）
  pages/worker.vue
Labels: officially-approved, ready-for-merge

#5261 カード上部の数値付近にテキスト「７日間移動平均」「７日間移動平均値をもとに算出」を追加
  components/DataViewBasicInfoPanel.vue
  components/DataViewDataSetPanel.vue
  components/MixedBarAndLineChart.vue
  components/MonitoringConfirmedCasesChart.vue
  components/MonitoringConsultationDeskReportChart.vue
  components/PositiveRateMixedChart.vue
  components/UntrackedRateMixedChart.vue
Labels: officially-approved, ready-for-merge

#5250 template に data.json をそのまま渡している箇所があるため，<script> タグ内で template に渡す値を限定する
  components/SiteTopUpper.vue
  components/cards/ConfirmedCasesAttributesCard.vue
  components/cards/ConfirmedCasesByMunicipalitiesCard.vue
  components/cards/ConfirmedCasesDetailsCard.vue
  components/cards/ConfirmedCasesNumberCard.vue
  components/cards/MetroCard.vue
  components/cards/PositiveNumberByDiagnosedDateCard.vue
  components/cards/SevereCaseCard.vue
  components/cards/TelephoneAdvisoryReportsNumberCard.vue
  components/cards/TestedNumberCard.vue
  layouts/default.vue
Labels: ready-for-merge

#5306 検査陽性者の状況チャートで使用していない「検査実施人数」に関するtypeとpropsを削除
  components/ConfirmedCasesDetailsTable.vue
  utils/formatConfirmedCases.ts
Labels: ready-for-merge

#5299 FORKED_SITES.md から市川市版の項目を削除する
  FORKED_SITES.md
Labels: ready-for-merge

#5297 派生したサイトの一覧に kyoto.stopcovid19.jp を追加
  FORKED_SITES.md
Labels: ready-for-merge

#5295 Fix 5292: potentiallysmall amount consumed
  components/MenuList.vue
  components/SideNavigation.vue
  components/StaticInfo.vue
  layouts/error.vue
Labels: ready-for-merge

#5324 「陽性者数（区市町村別）」の「陽性者数」の値に thousands separator を表示する
  components/cards/ConfirmedCasesByMunicipalitiesCard.vue
Labels: ready-for-merge

#5273 Card component の import の順序に一貫性がなく可読性が悪いので改善する
  components/CardsMonitoring.vue
  components/CardsReference.vue
  pages/cards/_card.vue
Labels: ready-for-merge

#5318 注釈に「重症基準の考え方はこちら」の外部リンクを追加
  components/cards/ConfirmedCasesDetailsCard.vue
  components/cards/SevereCaseCard.vue
Labels: officially-approved, ready-for-merge

#5348 RenovateのlockFileMaintenanceを有効にする
  .github/renovate.json
Labels: ready-for-merge

#5350 yarn.lockをリフレッシュ
  package.json
  yarn.lock
Labels: ready-for-merge

#5314 リンク系のコンポーネントを新たに作成したAppLink.vueに統合
  components/ActiveTokyoAlert.vue
  components/AppLink.vue
  components/DataView.vue
  components/DevelopmentModeMark.vue
  components/ExternalLink.vue
  components/LinkToInformationAboutEmergencyMeasure.vue
  components/LinkToInformationAboutRoadmap.vue
  components/MenuList.vue
  components/MetroBarChart.vue
  components/MonitoringCommentCard.vue
  components/OpenDataLink.vue
  components/SideNavigation.vue
  components/StaticInfo.vue
  components/WhatsNew.vue
  components/cards/ConfirmedCasesDetailsCard.vue
  components/cards/ConfirmedCasesNumberCard.vue
  components/cards/MonitoringItemsOverviewCard.vue
  components/cards/SevereCaseCard.vue
  pages/about.vue
  pages/flow.vue
  pages/parent.vue
  pages/worker.vue
  stylelint.config.js
  utils/urls.ts
Labels: ready-for-merge

#4118 インフォメーションのリンク文言を修正し、「相談の手順を見る」のボタンを削除
  components/StaticInfo.vue
Labels: officially-approved, ready-for-merge

#5360 StaticInfo.vueをAppLinkコンポーネントを使ったソースコードに修正
  components/StaticInfo.vue
Labels: ready-for-merge

#5358 「企業の皆様・はたらく皆様へ」ページへのコンテンツ追加
  pages/worker.vue
Labels: officially-approved, ready-for-merge
