Repository tokyo-metropolitan-gov/covid19, pull requests merged in 2020-09, with the labels that each got.

#5377 リンク切れのURL修正＆ナビダイヤルの表記修正
  components/SideNavigation.vue
  pages/contacts.vue
Labels: officially-approved, ready-for-merge

#5389 <template>, <script>, <style> の記述順序を統一する
  components/DataSelector.vue
  components/DataTable.vue
  components/DataViewBasicInfoPanel.vue
  components/DataViewDataSetPanel.vue
  components/DevelopmentModeMark.vue
  components/NoScript.vue
  components/OpenDataLink.vue
Labels: ready-for-merge

#5413 新規翻訳文字列の手動追加
  assets/locales/ja.json
Labels: i18n, need-i18n

#5416 Enable auto merge for patch
  .github/renovate.json
Labels: ready-for-merge

#5441 「検査陽性者の状況」カードに外部リンク追加
  components/cards/ConfirmedCasesDetailsCard.vue
Labels: officially-approved, ready-for-merge

#5439 カードによって注釈の位置の揺れがあるため統一する
  components/AgencyBarChart.vue
  components/MetroBarChart.vue
  components/cards/AgencyCard.vue
  components/cards/MetroCard.vue
Labels: ready-for-merge

#5442 CONTRIBUTORS.md の更新 (2020-09-17)
  CONTRIBUTORS.md
Labels: ready-for-merge

#5434 Googleタグマネージャの利用にともない@nuxtjs/gtmを追加
  nuxt.config.ts
  package.json
  yarn.lock
Labels: ready-for-merge

#5423 [Maintenance] GTMコンテナIDパラメーターの追加
  .github/workflows/deploy.yml
Labels: ready-for-merge

#5466 １つのパラグラフとなるようにi18nタグで囲う
  components/MonitoringCommentCard.vue
Labels: i18n, need-i18n

#5464 Fix automerge setting for patch
  .github/renovate.json
Labels: ready-for-merge
