Repository tokyo-metropolitan-gov/covid19, pull requests merged in 2020-06, with the labels that each got.

#4634 [refactor] グラフデータを表示するテーブルコンポーネントを追加
  components/AgencyBarChart.vue
  components/ConfirmedCasesByMunicipalitiesTable.vue
  components/ConfirmedCasesIncreaseRatioByWeekChart.vue
  components/DashedRectangleTimeBarChart.vue
  components/DataView.vue
  components/DataViewExpantionPanel.vue
  components/DataViewTable.vue
  components/MetroBarChart.vue
  components/MonitoringConfirmedCasesChart.vue
  components/MonitoringConsultationDeskReportChart.vue
  components/PositiveRateMixedChart.vue
  components/SevereCaseBarChart.vue
  components/TimeBarChart.vue
  components/TimeStackedBarChart.vue
  components/UntrackedRateMixedChart.vue
Labels: ready-for-merge

#4658 IE11向け日付フォーマット及びNodeList処理修正
  components/ConfirmedCasesByMunicipalitiesTable.vue
  components/DataTable.vue
  components/TimeStackedBarChart.vue
  nuxt-i18n.config.ts
Labels: ready-for-merge

#4599 [モニタリング指標] (6)PCR検査の陽性率グラフ下部のテーブルに検査実施人数の累計を追加
  components/PositiveRateMixedChart.vue
  components/cards/PositiveRateCard.vue
Labels: officially-approved, ready-for-merge

#4664 グラフの削除予告テキストを各カードに追加
  components/DataView.vue
  components/TimeBarChart.vue
  components/cards/ConsultationDeskReportsNumberCard.vue
  components/cards/InspectionPersonsNumberCard.vue
  components/cards/TestedCasesDetailsCard.vue
Labels: officially-approved, ready-for-merge

#4665 グラフ一覧にタブ切替を実装
  components/CardsTabs.vue
  components/SiteTopUpper.vue
  pages/index.vue
  pages/reference.vue
Labels: officially-approved, ready-for-merge

#4666 fix: ブラウザリサイズ時の `TypeError` エラーを修正
  components/cards/CardRow.vue
Labels: ready-for-merge

#4674 「東京アラート発動中」のコンポーネントを追加
  assets/variables.scss
  components/ActiveTokyoAlert.vue
  components/LinkToInformationAboutEmergencyMeasure.vue
  components/LinkToInformationAboutRoadmap.vue
  components/SiteTopUpper.vue
  components/WhatsNew.vue
  static/antenna.svg
Labels: officially-approved, ready-for-merge

#4683 +演算子による連結をテンプレート文字列に変更する
  pages/cards/_card.vue
Labels: ready-for-merge

#4684 タブのスタイルを調整
  components/CardsMonitoring.vue
  components/CardsReference.vue
  components/CardsTabs.vue
  pages/index.vue
Labels: officially-approved, ready-for-merge

#4691 .DataView-Share-Opener>svgの削除
  components/DataViewShare.vue
Labels: ready-for-merge

#4701 東京アラート＆緩和ステップ実装
  components/RelaxationStepCard.vue
  components/SiteTopUpper.vue
  components/TokyoAlertCard.vue
  components/WhatsNew.vue
  nuxt-i18n.config.ts
Labels: officially-approved, ready-for-merge

#4707 generate後のタブパーマリンクを機能させる
  pages/index.vue
Labels: ready-for-merge

#4702 +演算子による連結をテンプレート文字列に変更する
  components/DataView.vue
  components/DataViewShare.vue
  components/LanguageSelector.vue
  components/PositiveRateMixedChart.vue
  components/TimeStackedBarChart.vue
  components/UntrackedRateMixedChart.vue
  layouts/default.vue
Labels: ready-for-merge

#4708 getComplementedDate で本日の日付を今年のものと判定するようにする
  utils/formatDate.ts
Labels: ready-for-merge

#4717 緩和ステップの移行日時をブラウザ実装に依存しないように表示
  components/RelaxationStepCard.vue
  nuxt-i18n.config.ts
Labels: i18n, need-i18n, officially-approved, ready-for-merge

#4720 Add translation definitions
  assets/locales/ja.json
Labels: i18n, need-i18n

#4726 ステップ＆アラートのスタイルを調整
  components/RelaxationStepCard.vue
  components/TokyoAlertCard.vue
Labels: officially-approved, ready-for-merge

#4730 i18n generatorが認識可能な形式に変更
  components/RelaxationStepCard.vue
Labels: ready-for-merge

#4752 auto i18n generatorで使われていない翻訳キーを削除する部分をコメントアウト
  auto-i18n/i18n_generator.py
Labels: i18n

#4734 fix typo
  .github/workflows/i18n_generator.yml
Labels: i18n

#4737 モニタリング指標の項目の括弧が変換されるようにする
  components/MonitoringStatusOverviewTable.vue
Labels: i18n, ready-for-merge

#4749 FORKED_SITE 浜松市サイトのURLを最新のものに更新する
  FORKED_SITES.md
Labels: ready-for-merge

#4750 サイドナビの外部リンク項目を差し替え
  components/SideNavigation.vue
Labels: officially-approved, ready-for-merge

#4760 「（注）」を$tタグでかこむ
  components/cards/MonitoringStatusOverviewCard.vue
  components/cards/PositiveNumberByDiagnosedDateCard.vue
  components/cards/PositiveRateCard.vue
Labels: ready-for-merge

#4754 Feature/issue 4574 simplification
  plugins/vue-chart.ts
Labels: ready-for-merge

#4766 不要なimport文の削除
  types/shims-vue.d.ts
Labels: ready-for-merge

#4769 注釈のulのスタイルをlist-style-type: discに修正
  components/DataView.vue
  components/cards/ConfirmedCasesByMunicipalitiesCard.vue
  components/cards/ConfirmedCasesDetailsCard.vue
  components/cards/ConfirmedCasesNumberCard.vue
  components/cards/InspectionPersonsNumberCard.vue
  components/cards/TestedCasesDetailsCard.vue
  components/cards/TestedNumberCard.vue
Labels: officially-approved, ready-for-merge

#4773 feat: Complete Spanish translation developer docs
  docs/es/CONTRIBUTING.md
  docs/es/FOR_DEVELOPERS.md
  docs/es/README.md
Labels: ready-for-merge

#4779 getGraphSeriesColorの修正
  utils/colors.ts
Labels: ready-for-merge

#4778 Fix 4770: v-overlay Attribute
  layouts/default.vue
Labels: ready-for-merge

#4776 Feature/4765 aria accessibility table
  components/MonitoringStatusOverviewTable.vue
  pages/contacts.vue
Labels: ready-for-merge

#4784 Feature/4783 tableタグにaria-describedbyを追記する。
  pages/contacts.vue
Labels: ready-for-merge

#4792 fix: 2軸グラフのY軸のずれを修正
  components/PositiveRateMixedChart.vue
  components/UntrackedRateMixedChart.vue
Labels: ready-for-merge

#4791 削除予告のあるグラフ・チャートを削除する
  components/CardsReference.vue
  components/TestedCasesDetailsTable.vue
  components/cards/ConsultationDeskReportsNumberCard.vue
  components/cards/InspectionPersonsNumberCard.vue
  components/cards/TestedCasesDetailsCard.vue
  nuxt.config.ts
  ogp_invalidator/twitter_card_invalidator.py
  pages/cards/_card.vue
  ui-test/delete_fbcache.sh
  ui-test/list_fbcashe.sh
  ui-test/ogp_screenshot.py
Labels: officially-approved, ready-for-merge

#4816 ネストした3項演算をやめる
  components/cards/ConfirmedCasesByMunicipalitiesCard.vue
Labels: ready-for-merge

#4795 fix: `window.resize`時のグラフのレイアウト崩れを修正
  components/ConfirmedCasesIncreaseRatioByWeekChart.vue
  components/DashedRectangleTimeBarChart.vue
  components/DataView.vue
  components/MetroBarChart.vue
  components/MonitoringConfirmedCasesChart.vue
  components/MonitoringConsultationDeskReportChart.vue
  components/PositiveRateMixedChart.vue
  components/ScrollableChart.vue
  components/SevereCaseBarChart.vue
  components/TimeBarChart.vue
  components/TimeStackedBarChart.vue
  components/UntrackedRateMixedChart.vue
  plugins/vue-chart.ts
Labels: ready-for-merge

#4810 client-only の解除
  pages/index.vue
Labels: ready-for-merge

#4811 workerページ内の外部リンクを修正
  pages/worker.vue
Labels: officially-approved, ready-for-merge

#4817 dataへの代入をやめ直接returnで返す
  components/cards/ConfirmedCasesAttributesCard.vue
Labels: ready-for-merge

#4823 refactor: `vue-chart.ts` から DOM トラバースしているコードを削除
  components/ConfirmedCasesIncreaseRatioByWeekChart.vue
  components/DashedRectangleTimeBarChart.vue
  components/MonitoringConfirmedCasesChart.vue
  components/MonitoringConsultationDeskReportChart.vue
  components/PositiveRateMixedChart.vue
  components/ScrollableChart.vue
  components/SevereCaseBarChart.vue
  components/TimeBarChart.vue
  components/TimeStackedBarChart.vue
  components/UntrackedRateMixedChart.vue
  plugins/vue-chart.ts
Labels: ready-for-merge

#4829 緩和ステップのテキスト更新
  components/RelaxationStepCard.vue
Labels: officially-approved, ready-for-merge

#3704 日本語以外の設定の場合、区市町村別の陽性患者数表からふりがな表記の欄を外す
  components/cards/ConfirmedCasesByMunicipalitiesCard.vue
Labels: officially-answered, ready-for-merge

#4458 Feature/4454 fix monitoring status translation
  auto-i18n/i18n_generator.py
  components/MonitoringStatusOverviewTable.vue
Labels: i18n, ready-for-merge

#4833 Non-Null Assertion Operatorの除去
  plugins/vue-chart.ts
Labels: ready-for-merge

#4600 [モニタリング指標] 小数点以下の桁数を揃えたいの再対応
  components/ConfirmedCasesIncreaseRatioByWeekChart.vue
  components/MonitoringConfirmedCasesChart.vue
  components/PositiveRateMixedChart.vue
  components/UntrackedRateMixedChart.vue
  components/cards/ConfirmedCasesIncreaseRatioByWeekCard.vue
  components/cards/MonitoringConfirmedCasesNumberCard.vue
  components/cards/PositiveRateCard.vue
  components/cards/UntrackedRateCard.vue
  utils/monitoringStatusValueFormatters.ts
Labels: officially-approved, ready-for-merge

#4848 mapbox-glの削除
  nuxt.config.ts
  package.json
  static/map-test.html
  yarn.lock
Labels: ready-for-merge

#4851 「お子様をお持ちの皆様へ」ページ内テキスト修正
  pages/parent.vue
Labels: officially-approved, ready-for-merge

#4863 Hotfix/4859 modify dataset sort
  utils/formatConfirmedCases.ts
  utils/formatTable.ts
Labels: ready-for-merge

#4870 Control structures should use curly braces
  components/cards/MonitoringConfirmedCasesNumberCard.vue
  components/cards/PositiveRateCard.vue
  components/cards/UntrackedRateCard.vue
  utils/monitoringStatusValueFormatters.ts
Labels: ready-for-merge

#4875 import, requireで記載してるライブラリをpackage.jsonに追記する。
  package.json
  yarn.lock
Labels: ready-for-merge

#4884 #4839 [WIP]新型コロナウイルス感染症が心配なときにのボタンのサイズ調整
  pages/flow.vue
Labels: ready-for-merge

#4887 スクロールバーに関するスタイルを削除する
  components/ScrollableChart.vue
Labels: ready-for-merge

#4900 CONTRIBUTORS.md の更新 (2020-06-27)
  CONTRIBUTORS.md
Labels: ready-for-merge

#4889 ESLint, stylelintのバージョンアップ
  .eslintrc.js
  package.json
  yarn.lock
Labels: ready-for-merge

#4898 NuxtJSのバージョンアップなど
  nuxt.config.ts
  package.json
  yarn.lock
Labels: ready-for-merge
