Repository tokyo-metropolitan-gov/covid19, pull requests merged in 2020-05, with the labels that each got.

#3828 「検査実施件数」グラフのデザイン修正（保険適用分をわかりやすく）
  components/TimeStackedBarChart.vue
  components/cards/TestedNumberCard.vue
  package.json
Labels: officially-approved, ready-for-merge

#3802 titleTemplateが翻訳されるように修正
  layouts/default.vue
  nuxt.config.ts
Labels: ready-for-merge

#3687 「企業の皆様・はたらく皆様へ」の内容更新
  pages/worker.vue
Labels: officially-approved, ready-for-merge

#3839 日付を nuxt-i18n (vue-i18n) で翻訳し、フォーマットを統一させる
  nuxt-i18n.config.ts
Labels: ready-for-merge

#3840 「新型コロナウイルス感染症に関する東京都の支援策」のアイテム変更
  components/SideNavigation.vue
Labels: officially-approved, ready-for-merge

#3946 [ruby] 欠落していた括弧を追加
  components/ConfirmedCasesDetailsTable.vue
  components/TestedCasesDetailsTable.vue
Labels: i18n

#3902 不要なコンポーネントと参照を削除
  components/Heatmap.vue
  components/HeatmapLegend.vue
  components/MapCard.vue
  components/VisitorsBarChart.vue
  components/cards/ChiyodaVisitorsCard.vue
  components/cards/ShinjukuStMapCard.vue
  components/cards/ShinjukuVisitorsCard.vue
  components/cards/TokyoCityMapCard.vue
  components/cards/TokyoStMapCard.vue
  ui-test/ogp_screenshot.py
Labels: ready-for-merge

#3926 フォントサイズを相対指定に修正
  assets/global.scss
  assets/variables.scss
  components/AgencyBarChart.vue
  components/ConfirmedCasesByMunicipalitiesTable.vue
  components/DataSelector.vue
  components/DataTable.vue
  components/DataView.vue
  components/DataViewBasicInfoPanel.vue
  components/DevelopmentModeMark.vue
  components/ExternalLink.vue
  components/LanguageSelector.vue
  components/MenuList.vue
  components/MetroBarChart.vue
  components/OpenDataLink.vue
  components/PageHeader.vue
  components/SideNavigation.vue
  components/SourceLink.vue
  components/StaticCard.vue
  components/TestedCasesDetailsTable.vue
  components/TimeStackedBarChart.vue
  components/WhatsNew.vue
  components/cards/TestedCasesDetailsCard.vue
  components/cards/TestedNumberCard.vue
  layouts/print.vue
  pages/contacts.vue
  pages/flow.vue
  pages/index.vue
Labels: ready-for-merge

#3936 CONTRIBUTORS.md の更新・修正 (2020-05-05)
  CONTRIBUTORS.md
Labels: ready-for-merge

#3938 ウェブブラウザの名前を修正
  pages/about.vue
Labels: ready-for-merge

#3956 FORKED_SITES.mdから九州を削除
  FORKED_SITES.md
Labels: ready-for-merge

#3969 「検査実施状況」チャート・「検査実施件数」グラフの注釈変更
  assets/locales/ja.json
  components/TimeStackedBarChart.vue
  components/cards/TestedCasesDetailsCard.vue
Labels: officially-approved, ready-for-merge

#3968 「検査実施状況」チャートの注釈変更
  assets/locales/ja.json
  components/cards/TestedCasesDetailsCard.vue
Labels: officially-approved, ready-for-merge

#3987 「検査実施人数」「陽性患者数」の注釈変更
  components/cards/ConfirmedCasesNumberCard.vue
  components/cards/InspectionPersonsNumberCard.vue
Labels: officially-approved

#3970 Hotfix/3958 Fixing source link behavior with anchor
  pages/flow.vue
Labels: ready-for-merge

#4017 「検査実施状況」チャートに保健所分と民間分を掲載
  components/TestedCasesDetailsTable.vue
  utils/formatTestedCases.ts
Labels: officially-approved, ready-for-merge

#4027 FORKED_SITES.md に市川市を追加する
  FORKED_SITES.md
Labels: ready-for-merge

#4040 thタグにscope="row"を追加する
  components/AgencyBarChart.vue
  components/DataTable.vue
  components/MetroBarChart.vue
  components/TimeBarChart.vue
  components/TimeStackedBarChart.vue
Labels: ready-for-merge

#4044 [hotfix]「検査実施状況」と「検査実施人数」の間で区切る
  pages/index.vue
Labels: officially-approved, ready-for-merge

#4052 Hotfix/4030 Flow Text Update 相談フローページの文言改修
  pages/flow.vue
Labels: officially-approved, ready-for-merge

#4079 新規グラフ「判明日別陽性患者数」の作成
  components/TimeBarChart.vue
  components/cards/PositiveNumberByDiagnosedDateCard.vue
  nuxt.config.ts
  pages/cards/_card.vue
  pages/index.vue
  ui-test/ogp_screenshot.py
Labels: officially-approved, waiting-for-confirmation

#4053 新規グラフ「陽性率」の作成（積み上げ棒グラフ＋折れ線グラフの２軸グラフ）
  components/PositiveRate2MixedChart.vue
  components/PositiveRateMixedChart.vue
  components/cards/PositiveRateFirstCard.vue
  components/cards/PositiveRateSecondCard.vue
  data/positive_rate.json
  nuxt.config.ts
  pages/cards/_card.vue
  pages/index.vue
  plugins/vue-chart.ts
  ui-test/ogp_screenshot.py
Labels: officially-approved, waiting-for-confirmation

#4096 新規グラフ「判明日別陽性患者数」「陽性率」追加
  components/DataView.vue
  components/PositiveRate2MixedChart.vue
  components/PositiveRateMixedChart.vue
  components/TimeBarChart.vue
  components/cards/PositiveNumberByDiagnosedDateCard.vue
  components/cards/PositiveRateFirstCard.vue
  components/cards/PositiveRateSecondCard.vue
  data/positive_by_diagnosed.json
  data/positive_rate.json
  nuxt.config.ts
  pages/cards/_card.vue
  pages/index.vue
  plugins/vue-chart.ts
  ui-test/ogp_screenshot.py
Labels: ready-for-merge, waiting-for-confirmation

#4122 add support dataKind params
  components/TimeStackedBarChart.vue
Labels: ready-for-merge

#4121 fix yAxes issue
  components/TimeBarChart.vue
Labels: ready-for-merge

#4107 Completed translation of FOR_DEVELOPER.md for zh_TW
  docs/zh_TW/FOR_DEVELOPERS.md
Labels: ready-for-merge

#4081 OGPのDescriptionが正しく翻訳されるように修正
  layouts/default.vue
Labels: ready-for-merge

#4080 issue-4078/お問い合わせ先一覧ページのコンテンツ修正
  pages/contacts.vue
Labels: officially-approved, ready-for-merge

#4104 「検査陽性者の状況」に項目を追加
  components/ConfirmedCasesDetailsTable.vue
  components/cards/ConfirmedCasesDetailsCard.vue
  utils/formatConfirmedCases.ts
Labels: officially-approved, ready-for-merge

#4074 issue-4070/翻訳キーの修正
  pages/parent.vue
Labels: ready-for-merge

#4123 「判明日別陽性患者数」グラフから不要な注釈を削除
  components/cards/PositiveNumberByDiagnosedDateCard.vue
Labels: officially-approved, ready-for-merge

#4109 「検査実施件数」グラフに注釈を追加
  components/TimeStackedBarChart.vue
  components/cards/TestedNumberCard.vue
Labels: officially-approved, ready-for-merge

#4108 ２枚の「陽性率」のグラフを１枚に統合する
  components/PositiveRate2MixedChart.vue
  components/PositiveRateMixedChart.vue
  components/cards/PositiveRateCard.vue
  components/cards/PositiveRateSecondCard.vue
  nuxt.config.ts
  pages/cards/_card.vue
  pages/index.vue
  ui-test/ogp_screenshot.py
Labels: officially-approved, ready-for-merge

#4145 PositiveRateMixedChart.vue の thタグに scope属性がない問題の修正
  components/PositiveRateMixedChart.vue
Labels: ready-for-merge

#4139 issue-4124/検査陽性者の状況の右側が切れていて読めない
  components/ConfirmedCasesDetailsTable.vue
Labels: ready-for-merge

#4132 北九州市版を追加
  FORKED_SITES.md
Labels: ready-for-merge

#4094 YAMLファイルのインデントなどの修正
  .github/auto-merge-bot.config.yml
  .github/labeler.yml
  .github/workflows/deploy.yml
  .github/workflows/i18n_generator.yml
  .github/workflows/pr-labeler.yml
  docker-compose.yml
  ogp_invalidator/docker-compose.yml
Labels: ready-for-merge

#4146 陽性率グラフのテーブルに陽性者数と陰性者数の合計値を表示
  components/PositiveRateMixedChart.vue
  components/cards/PositiveRateCard.vue
Labels: officially-approved, ready-for-merge

#3868 陽性患者の属性にページングを追加
  components/ConfirmedCasesByMunicipalitiesTable.vue
  components/DataTable.vue
Labels: officially-approved, ready-for-merge

#4210 remove lazy render
  components/cards/ConfirmedCasesAttributesCard.vue
Labels: ready-for-merge

#4204 「判明日別陽性者数」グラフの最新人数に対する説明文を変更したい
  components/DataViewBasicInfoPanel.vue
  components/cards/PositiveNumberByDiagnosedDateCard.vue
Labels: officially-approved, ready-for-merge

#4197 「検査実施件数」グラフの注釈を修正
  components/cards/TestedNumberCard.vue
Labels: officially-approved, ready-for-merge

#4196 README内のリンクテキストを具体的にする
  README.md
Labels: ready-for-merge

#4289 37.5℃以上の発熱が4日以上 の受診目安を修正
  assets/locales/ja.json
Labels: officially-approved, ready-for-merge

#4265 update FORKED_SITES
  FORKED_SITES.md
Labels: ready-for-merge

#4179 YAMLファイルから無駄な空白の削除
  .github/labeler.yml
Labels: ready-for-merge

#4333 モニタリング指標(1) 新規陽性者数グラフの追加
  components/SimpleMixedChart.vue
  components/cards/MonitoringConfirmedCasesNumberCard.vue
  nuxt.config.ts
  pages/cards/_card.vue
  pages/index.vue
  ui-test/ogp_screenshot.py
Labels: officially-approved, ready-for-merge

#4336 モニタリング指標(2) 接触歴等不明率グラフの追加
  components/UntrackedRateMixedChart.vue
  components/cards/UntrackedRateCard.vue
  nuxt.config.ts
  pages/cards/_card.vue
  pages/index.vue
  ui-test/ogp_screenshot.py
Labels: officially-approved, ready-for-merge

#4332 モニタリング指標(3)週単位の陽性者増加比グラフの追加
  components/ConfirmedCasesIncreaseRatioByWeekChart.vue
  components/cards/ConfirmedCasesIncreaseRatioByWeekCard.vue
  nuxt.config.ts
  pages/cards/_card.vue
  pages/index.vue
  plugins/vue-chart.ts
  ui-test/ogp_screenshot.py
  utils/colors.ts
Labels: officially-approved, ready-for-merge

#4329 モニタリング指標(4)重症患者数グラフの追加
  components/SevereCaseBarChart.vue
  components/cards/SevereCaseCard.vue
  nuxt.config.ts
  pages/cards/_card.vue
  pages/index.vue
  ui-test/ogp_screenshot.py
Labels: officially-approved, ready-for-merge

#4364 モニタリング指標(5)入院患者数グラフの追加
  components/DashedRectangleTimeBarChart.vue
  components/cards/HospitalizedNumberCard.vue
  nuxt.config.ts
  pages/cards/_card.vue
  pages/index.vue
  plugins/vue-chart.ts
  ui-test/ogp_screenshot.py
Labels: officially-approved, ready-for-merge

#4330 モニタリング指標(6) タイトル変更＋注釈移動
  components/PositiveRateMixedChart.vue
  components/cards/PositiveRateCard.vue
Labels: officially-approved, ready-for-merge

#4334 (PR) [モニタリング指標] 総括表 [新規] テーブル組み
  components/MonitoringStatusOverviewTable.vue
  components/cards/MonitoringStatusOverviewCard.vue
  nuxt.config.ts
  pages/cards/_card.vue
  pages/index.vue
  ui-test/ogp_screenshot.py
  utils/formatMonitoringStatus.ts
Labels: officially-approved, ready-for-merge

#4339 「TOKYOおはようスクール」のリンク追加
  pages/parent.vue
Labels: officially-approved, ready-for-merge

#4298 (PR) 「検査陽性者の状況」テーブルを横均等7分割から縦の積み上げにする
  components/ConfirmedCasesDetailsTable.vue
  components/cards/ConfirmedCasesDetailsCard.vue
  utils/formatConfirmedCases.ts
Labels: officially-approved, ready-for-merge

#3208 プロパティ名を修正
  components/cards/ConfirmedCasesNumberCard.vue
  pages/cards/_card.vue
Labels: ready-for-merge

#4423 #4413 [モニタリング指標：残作業] 前日比の表示
  components/PositiveRateMixedChart.vue
  components/SimpleMixedChart.vue
  components/UntrackedRateMixedChart.vue
  components/cards/PositiveRateCard.vue
  components/cards/UntrackedRateCard.vue
Labels: officially-approved, ready-for-merge

#4429 「東京都緊急事態措置について」をコンポーネント化
  components/LinkToInformationAboutEmergencyMeasure.vue
  components/WhatsNew.vue
Labels: ready-for-merge

#4439 破線矩形のふとさを2pxに変更
  components/DashedRectangleTimeBarChart.vue
Labels: ready-for-merge

#4440 Fix 4437: Correcting use of method adhered to a mixed-type variable
  components/MetroBarChart.vue
Labels: ready-for-merge

#4442 CONTRIBUTORS.md の更新 (2020-05-24)
  CONTRIBUTORS.md
Labels: ready-for-merge

#4449 [refactor] `DataView.vue` から SNS シェアに関するコードを分離
  components/DataView.vue
  components/DataViewShare.vue
Labels: ready-for-merge

#4424 モニタリング指標(残作業) 補助線の追加
  components/ConfirmedCasesIncreaseRatioByWeekChart.vue
  components/SimpleMixedChart.vue
  components/UntrackedRateMixedChart.vue
  components/cards/ConfirmedCasesIncreaseRatioByWeekCard.vue
  components/cards/MonitoringConfirmedCasesNumberCard.vue
  components/cards/UntrackedRateCard.vue
  utils/colors.ts
Labels: officially-approved, ready-for-merge

#4480 Fix import duplication
  pages/cards/_card.vue
Labels: ready-for-merge

#4485 [refactor] `DataView.vue` から DataTable に関するコードを分離
  components/DataView.vue
  components/DataViewTable.vue
Labels: ready-for-merge

#4489 [FORKED_SITES.md] 表記の統一
  FORKED_SITES.md
Labels: ready-for-merge

#4493 「ロードマップについて」の外部リンクボタン作成
  assets/variables.scss
  components/LinkToInformationAboutRoadmap.vue
  components/WhatsNew.vue
  pages/index.vue
Labels: officially-approved, ready-for-merge

#4494 #4490サイドナビの外部リンクを変更（緊急事態宣言解除対応）
  components/SideNavigation.vue
Labels: officially-approved, ready-for-merge

#4452 [refactor] `PositiveRateMixedChart.vue`, `SimpleMixedChart.vue` から未使用メソッドを削除
  components/PositiveRateMixedChart.vue
  components/SimpleMixedChart.vue
Labels: ready-for-merge

#4453 [refactor] `SevereCaseBarChart.vue` から累計値に関するコードを削除
  components/SevereCaseBarChart.vue
  components/cards/SevereCaseCard.vue
Labels: ready-for-merge

#4499 カードとその個別ページでタイトルや更新時刻を揃える
  components/DataView.vue
  pages/cards/_card.vue
Labels: ready-for-merge

#4514 #4508「企業の皆様・はたらく皆様へ」内の文章訂正
  pages/worker.vue
Labels: officially-approved, ready-for-merge

#4516 #4515「検査実施人数」グラフタイトル変更・「モニタリング指標」注釈修正
  components/cards/InspectionPersonsNumberCard.vue
  components/cards/MonitoringStatusOverviewCard.vue
Labels: officially-approved, ready-for-merge

#4533 [refactor] `DataView.vue` から不要なスタイルやスロットなどを削除
  components/AgencyBarChart.vue
  components/DataView.vue
  components/DataViewBasicInfoPanel.vue
  components/MetroBarChart.vue
Labels: ready-for-merge

#4559 [refactor] PositiveRateCard.vue および UntrackedRateCard.vue の定数統合
  components/PositiveRateMixedChart.vue
  components/UntrackedRateMixedChart.vue
  components/cards/PositiveRateCard.vue
  components/cards/UntrackedRateCard.vue
Labels: ready-for-merge

#4544 +演算子による連結をテンプレート文字列に変更する
  pages/cards/_card.vue
Labels: ready-for-merge

#4557 `SimpleMixedChart.vue` を各グラフごとのコンポーネントへ分割
  components/MonitoringConfirmedCasesChart.vue
  components/MonitoringConsultationDeskReportChart.vue
  components/cards/MonitoringConfirmedCasesNumberCard.vue
  components/cards/MonitoringConsultationDeskReportsNumberCard.vue
Labels: ready-for-merge

#4547 #4545グラフ・表の並び順変更
  pages/index.vue
Labels: officially-approved, ready-for-merge

#4560 CONTRIBUTORS.md の更新 (2020-05-28)
  CONTRIBUTORS.md
Labels: ready-for-merge

#4512 #4422 新規患者に関する報告件数の推移で0人の日に0人のポップアップ表示させる
  components/TimeBarChart.vue
Labels: ready-for-merge

#4537 Bump actions/cache from v1 to v2
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  .github/workflows/ogp_builder.yml
  .github/workflows/screenshot.yml
  .github/workflows/staging.yml
Labels: ready-for-merge

#4580 [モニタリング指標] 総括表 go_threshold が非nullの場合に結合セルでデータを表示
  components/MonitoringStatusOverviewTable.vue
Labels: officially-approved, ready-for-merge

#4582 [refactor] グラフの注釈に関するスタイルをまとめる
  components/AgencyBarChart.vue
  components/DataTable.vue
  components/DataView.vue
  components/MetroBarChart.vue
  components/PositiveRateMixedChart.vue
  components/TimeStackedBarChart.vue
  components/UntrackedRateMixedChart.vue
  components/cards/MonitoringStatusOverviewCard.vue
  components/cards/PositiveRateCard.vue
  components/cards/TestedCasesDetailsCard.vue
  components/cards/TestedNumberCard.vue
  components/cards/UntrackedRateCard.vue
Labels: ready-for-merge

#4587 branch-protection-botの削除
  .github/workflows/deploy.yml
Labels: ready-for-merge

#4594 モニタリング指標の補助線の凡例を線状にする
  components/ConfirmedCasesIncreaseRatioByWeekChart.vue
  components/MonitoringConfirmedCasesChart.vue
  components/UntrackedRateMixedChart.vue
Labels: officially-approved, ready-for-merge

#4595 代入をやめ直接returnするよう修正する
  utils/formatConfirmedCases.ts
  utils/formatTestedCases.ts
Labels: ready-for-merge

#4232 日付のフォーマットの多言語対応
  components/AgencyBarChart.vue
  components/DataView.vue
  components/PositiveRateMixedChart.vue
  components/TimeBarChart.vue
  components/TimeStackedBarChart.vue
  components/WhatsNew.vue
  components/cards/AgencyCard.vue
  components/cards/ConfirmedCasesAttributesCard.vue
  components/cards/ConfirmedCasesByMunicipalitiesCard.vue
  components/cards/MetroCard.vue
  nuxt-i18n.config.ts
  pages/index.vue
  utils/formatDate.ts
  utils/formatTable.ts
Labels: i18n, ready-for-merge

#4636 折れ線グラフの凡例を線状にする
  components/MonitoringConfirmedCasesChart.vue
  components/MonitoringConsultationDeskReportChart.vue
  components/PositiveRateMixedChart.vue
  components/UntrackedRateMixedChart.vue
Labels: ready-for-merge

#4645 trailing spaces
  .github/workflows/deploy.yml
Labels: ready-for-merge
