Repository tokyo-metropolitan-gov/covid19, pull requests merged in 2020-07, with the labels that each got.

#4912 require('webpack')の削除
  nuxt.config.ts
Labels: ready-for-merge

#4916 総括表の「目安となる数値」削除
  components/MonitoringStatusOverviewTable.vue
  components/cards/MonitoringStatusOverviewCard.vue
  utils/formatMonitoringStatus.ts
Labels: officially-approved, ready-for-merge

#4917 グラフ内の補助線削除
  components/ConfirmedCasesIncreaseRatioByWeekChart.vue
  components/MonitoringConfirmedCasesChart.vue
  components/UntrackedRateMixedChart.vue
  components/cards/ConfirmedCasesIncreaseRatioByWeekCard.vue
  components/cards/MonitoringConfirmedCasesNumberCard.vue
  components/cards/UntrackedRateCard.vue
Labels: officially-approved, ready-for-merge

#4927 モニタリング指標のタイトルの先頭に「旧」を追加・タブ直下に注意書きを追加
  components/CardsMonitoring.vue
  components/cards/ConfirmedCasesIncreaseRatioByWeekCard.vue
  components/cards/HospitalizedNumberCard.vue
  components/cards/MonitoringConfirmedCasesNumberCard.vue
  components/cards/MonitoringConsultationDeskReportsNumberCard.vue
  components/cards/MonitoringStatusOverviewCard.vue
  components/cards/PositiveRateCard.vue
  components/cards/SevereCaseCard.vue
  components/cards/UntrackedRateCard.vue
Labels: officially-approved, ready-for-merge

#4936 fix #4935: Add accepted languages
  TRANSLATION.md
Labels: documentation, ready-for-merge

#4933 NuxtJSのバージョンアップなど
  package.json
  yarn.lock
Labels: ready-for-merge

#4938 1つのカードに複数の指標値をタイトル付きで記載できるようにする。
  components/ConfirmedCasesIncreaseRatioByWeekChart.vue
  components/DashedRectangleTimeBarChart.vue
  components/DataView.vue
  components/DataViewDataSetPanel.vue
  components/MonitoringConfirmedCasesChart.vue
  components/MonitoringConsultationDeskReportChart.vue
  components/PositiveRateMixedChart.vue
  components/SevereCaseBarChart.vue
  components/UntrackedRateMixedChart.vue
  components/cards/ConfirmedCasesIncreaseRatioByWeekCard.vue
  components/cards/HospitalizedNumberCard.vue
  components/cards/MonitoringConfirmedCasesNumberCard.vue
  components/cards/MonitoringConsultationDeskReportsNumberCard.vue
  components/cards/PositiveRateCard.vue
  components/cards/SevereCaseCard.vue
  components/cards/UntrackedRateCard.vue
Labels: officially-approved, ready-for-merge

#4924 ConfigurationをNuxtConfigに変更する
  nuxt.config.ts
  package.json
  yarn.lock
Labels: ready-for-merge

#4944 VuetifyのData tablesに関するsass変数の値をカスタマイズ
  assets/variables.scss
  components/DataViewTable.vue
Labels: officially-approved, ready-for-merge

#4962 [モニタリング項目](1)(6)(7)グラフタイトルの変更
  components/cards/HospitalizedNumberCard.vue
  components/cards/MonitoringConfirmedCasesNumberCard.vue
  components/cards/SevereCaseCard.vue
Labels: officially-approved, ready-for-merge

#4971 旧モニタリング指標(3) 削除予告追加・配置変更
  components/CardsMonitoring.vue
  components/CardsReference.vue
  components/ConfirmedCasesIncreaseRatioByWeekChart.vue
  components/cards/ConfirmedCasesIncreaseRatioByWeekCard.vue
Labels: officially-approved, ready-for-merge

#4973 注釈のスタイル変更および内容修正
  components/cards/PositiveNumberByDiagnosedDateCard.vue
  components/cards/TestedNumberCard.vue
Labels: officially-approved, ready-for-merge

#4974 delete RequestSuspensionCard
  components/RequestSuspensionCard.vue
  components/SiteTopUpper.vue
Labels: officially-approved, ready-for-merge

#4975 Fix #4972: Change Tab Caption
  components/CardsMonitoring.vue
  components/CardsTabs.vue
Labels: officially-approved, ready-for-merge

#4963 "受診相談窓口における相談件数" のタイトル変更および配置変更
  components/CardsMonitoring.vue
  components/CardsReference.vue
  components/MonitoringConsultationDeskReportChart.vue
  components/cards/MonitoringConsultationDeskReportsNumberCard.vue
  utils/formatMonitoringStatus.ts
Labels: officially-approved, ready-for-merge

#4979 モニタリング項目(3)
  components/UntrackedRateMixedChart.vue
  components/cards/UntrackedRateCard.vue
Labels: officially-approved, ready-for-merge

#4978 モニタリング項目(4)
  components/PositiveRateMixedChart.vue
  components/cards/PositiveRateCard.vue
  utils/colors.ts
Labels: officially-approved, ready-for-merge

#4966 モニタリング項目(2)(5)新規グラフ作成
  components/CardsMonitoring.vue
  components/MixedBarAndLineChart.vue
  components/cards/ConsultationAboutFeverNumberCard.vue
  components/cards/TokyoRulesApplicationNumberCard.vue
  nuxt.config.ts
  pages/cards/_card.vue
  ui-test/ogp_screenshot.py
Labels: officially-approved, ready-for-merge

#4967 新モニタリング項目 総括表
  assets/monitoringItemsTableCommon.scss
  components/CardsMonitoring.vue
  components/MonitoringItemsOverviewTableInfectionStatus.vue
  components/MonitoringItemsOverviewTableMedicalSystem.vue
  components/MonitoringItemsOverviewTableValueWithTranslatableUnit.vue
  components/MonitoringStatusOverviewTable.vue
  components/cards/MonitoringItemsOverviewCard.vue
  components/cards/MonitoringStatusOverviewCard.vue
  nuxt.config.ts
  pages/cards/_card.vue
  ui-test/ogp_screenshot.py
  utils/formatMonitoringItems.ts
  utils/formatMonitoringStatus.ts
  utils/monitoringStatusValueFormatters.ts
Labels: officially-approved, ready-for-merge

#5002 モニタリング項目(4)の検査人数の値を小数点以下１桁＋３桁区切りに
  components/PositiveRateMixedChart.vue
  components/cards/PositiveRateCard.vue
Labels: officially-approved, ready-for-merge

#4954 @nuxt/typescript-build, eslint, nuxt-i18n のバージョンアップ
  components/ConfirmedCasesIncreaseRatioByWeekChart.vue
  nuxt.config.ts
  package.json
  yarn.lock
Labels: dependencies, ready-for-merge

#5019 FORKED_SITES.mdから福井県（丹南ケーブルテレビ運営）サイトを削除
  FORKED_SITES.md
Labels: ready-for-merge

#5013 Update FORKED_SITES.md
  FORKED_SITES.md
Labels: ready-for-merge

#5012 docker-compose.ymlの不要なオプション指定を削除する
  docker-compose.yml
Labels: ready-for-merge

#4897 fix: /?tab=referenceに直アクセスできない問題を修正
  components/CardsTabs.vue
  components/ScrollableChart.vue
  pages/index.vue
  plugins/vue-chart.ts
  utils/tab-event-bus.ts
Labels: ready-for-merge

#5028 モニタリング項目の注釈を変更
  components/cards/MonitoringItemsOverviewCard.vue
Labels: officially-approved, ready-for-merge

#5023 検査実施件数のテーブルのthにwidthを設定する
  assets/variables.scss
  components/DataTable.vue
  components/DataViewExpantionPanel.vue
  components/DataViewTable.vue
  components/TimeStackedBarChart.vue
Labels: officially-approved, ready-for-merge

#5029 モニタリング項目の分析・総括コメントカードの追加
  auto-i18n/i18n_generator.py
  components/MonitoringCommentCard.vue
  components/MonitoringCommentFrame.vue
  components/SiteTopUpper.vue
Labels: officially-approved, ready-for-merge

#5030 Issue 5024: Drop the Card 週単位の陽性者増加比
  components/CardsReference.vue
  components/cards/ConfirmedCasesIncreaseRatioByWeekCard.vue
  nuxt.config.ts
  pages/cards/_card.vue
  ui-test/ogp_screenshot.py
Labels: officially-approved, ready-for-merge

#5037 TimeBarChartの修正など
  components/PositiveRateMixedChart.vue
  components/TimeBarChart.vue
Labels: ready-for-merge

#5042 vue-spinner 1.0.4, autoprefixer 9.8.5
  package.json
  yarn.lock
Labels: dependencies, ready-for-merge

#5054 2軸グラフの横軸右側のマスクを修正
  plugins/vue-chart.ts
Labels: ready-for-merge

#5056 nuxt-i18n の自動リダイレクトの停止と <link rel=alternative> タグの出力
  layouts/default.vue
  nuxt-i18n.config.ts
  nuxt.config.ts
  pages/cards/_card.vue
  pages/print/flow.vue
  utils/i18nUtils.ts
Labels: ready-for-merge

#5057 タブ切り替え ->「テーブルを表示」のレイアウト崩れを修正
  components/cards/CardRow.vue
  pages/index.vue
  plugins/vue-chart.ts
Labels: ready-for-merge

#3484 ステージングに対する Lighthouse CI の追加
  .github/workflows/audit-staging.yml
Labels: ready-for-merge

#5068 ライブラリの自動アップデートのためにRenovateを導入
  .github/renovate.json
Labels: ready-for-merge

#5074 依存関係にvue-meta 2.4.0を追加する。
  package.json
Labels: ready-for-merge

#5095 CONTRIBUTORS.md の更新 (2020-07-25)
  CONTRIBUTORS.md
Labels: ready-for-merge

#5091 Mapbox 関連のコードを削除
  layouts/default.vue
  static/tiles/20200201/corona_heatmap/hourly/8/metadata.json
  static/tiles/20200202/corona_heatmap/hourly/8/metadata.json
  static/tiles/20200203/corona_heatmap/hourly/8/metadata.json
  static/tiles/20200204/corona_heatmap/hourly/8/metadata.json
  static/tiles/20200205/corona_heatmap/hourly/8/metadata.json
  static/tiles/20200206/corona_heatmap/hourly/8/metadata.json
  static/tiles/20200207/corona_heatmap/hourly/8/metadata.json
  static/tiles/20200208/corona_heatmap/hourly/8/metadata.json
  static/tiles/20200209/corona_heatmap/hourly/8/metadata.json
  static/tiles/20200210/corona_heatmap/hourly/8/metadata.json
  static/tiles/20200211/corona_heatmap/hourly/8/metadata.json
  static/tiles/20200212/corona_heatmap/hourly/8/metadata.json
  static/tiles/20200213/corona_heatmap/hourly/8/metadata.json
  static/tiles/20200214/corona_heatmap/hourly/8/metadata.json
  static/tiles/20200215/corona_heatmap/hourly/8/metadata.json
  static/tiles/20200216/corona_heatmap/hourly/8/metadata.json
  static/tiles/20200217/corona_heatmap/hourly/8/metadata.json
  static/tiles/20200218/corona_heatmap/hourly/8/metadata.json
  static/tiles/20200219/corona_heatmap/hourly/8/metadata.json
  static/tiles/20200220/corona_heatmap/hourly/8/metadata.json
  static/tiles/20200221/corona_heatmap/hourly/8/metadata.json
  static/tiles/20200222/corona_heatmap/hourly/8/metadata.json
  static/tiles/20200223/corona_heatmap/hourly/8/metadata.json
  static/tiles/20200224/corona_heatmap/hourly/8/metadata.json
  static/tiles/20200225/corona_heatmap/hourly/8/metadata.json
  static/tiles/20200226/corona_heatmap/hourly/8/metadata.json
  static/tiles/20200227/corona_heatmap/hourly/8/metadata.json
  static/tiles/20200228/corona_heatmap/hourly/8/metadata.json
  static/tiles/20200229/corona_heatmap/hourly/8/metadata.json
  static/tiles/20200301/corona_heatmap/hourly/8/metadata.json
  static/tiles/20200302/corona_heatmap/hourly/8/metadata.json
  static/tiles/20200303/corona_heatmap/hourly/8/metadata.json
  static/tiles/20200304/corona_heatmap/hourly/8/metadata.json
  static/tiles/20200305/corona_heatmap/hourly/8/metadata.json
  static/tiles/20200306/corona_heatmap/hourly/8/metadata.json
  static/tiles/20200307/corona_heatmap/hourly/8/metadata.json
  static/tiles/20200308/corona_heatmap/hourly/8/metadata.json
  static/tiles/20200309/corona_heatmap/hourly/8/metadata.json
  static/tiles/20200310/corona_heatmap/hourly/8/metadata.json
Labels: ready-for-merge

#5076 Lighthouseスコアの改善
  components/AgencyBarChart.vue
  components/ConfirmedCasesIncreaseRatioByWeekChart.vue
  components/DashedRectangleTimeBarChart.vue
  components/MetroBarChart.vue
  components/MixedBarAndLineChart.vue
  components/MonitoringConfirmedCasesChart.vue
  components/MonitoringConsultationDeskReportChart.vue
  components/PositiveRateMixedChart.vue
  components/SevereCaseBarChart.vue
  components/SideNavigation.vue
  components/TimeBarChart.vue
  components/TimeStackedBarChart.vue
  components/UntrackedRateMixedChart.vue
  components/cards/AgencyCard.vue
  components/cards/ConfirmedCasesAttributesCard.vue
  components/cards/ConfirmedCasesByMunicipalitiesCard.vue
  components/cards/ConfirmedCasesDetailsCard.vue
  components/cards/ConfirmedCasesNumberCard.vue
  components/cards/ConsultationAboutFeverNumberCard.vue
  components/cards/HospitalizedNumberCard.vue
  components/cards/MetroCard.vue
  components/cards/MonitoringConfirmedCasesNumberCard.vue
  components/cards/MonitoringConsultationDeskReportsNumberCard.vue
  components/cards/MonitoringItemsOverviewCard.vue
  components/cards/PositiveNumberByDiagnosedDateCard.vue
  components/cards/PositiveRateCard.vue
  components/cards/SevereCaseCard.vue
  components/cards/TelephoneAdvisoryReportsNumberCard.vue
  components/cards/TestedNumberCard.vue
  components/cards/TokyoRulesApplicationNumberCard.vue
  components/cards/UntrackedRateCard.vue
  layouts/default.vue
Labels: ready-for-merge

#5071 「新規患者に関する報告件数の推移」グラフに外部リンク追加、注釈の体裁整理
  components/cards/ConfirmedCasesNumberCard.vue
Labels: officially-approved, ready-for-merge

#5077 日付の表示形式を揃える
  components/DashedRectangleTimeBarChart.vue
  components/DataViewTable.vue
  components/MetroBarChart.vue
  components/MixedBarAndLineChart.vue
  components/MonitoringConfirmedCasesChart.vue
  components/MonitoringConsultationDeskReportChart.vue
  components/PositiveRateMixedChart.vue
  components/SevereCaseBarChart.vue
  components/TimeBarChart.vue
  components/TimeStackedBarChart.vue
  components/UntrackedRateMixedChart.vue
  components/cards/ConfirmedCasesAttributesCard.vue
  components/cards/PositiveNumberByDiagnosedDateCard.vue
  utils/formatDate.ts
  utils/formatDayBeforeRatio.ts
Labels: ready-for-merge

#5101 relにnoopenerを追加する。
  components/SideNavigation.vue
Labels: ready-for-merge

#5104 「検査陽性者の状況」注釈の修正・体裁整理
  components/cards/ConfirmedCasesDetailsCard.vue
Labels: officially-approved, ready-for-merge

#5105 お問い合わせ内容・局名テキスト修正
  pages/contacts.vue
Labels: officially-approved, ready-for-merge
