Repository tokyo-metropolitan-gov/covid19, pull requests merged in 2020-04, with the labels that each got.

#2705 グラフの色をアップデートする
  components/AgencyBarChart.vue
  components/MetroBarChart.vue
  components/TimeBarChart.vue
  components/TimeStackedBarChart.vue
  components/VisitorsBarChart.vue
  utils/colors.ts
Labels: accessibility, ready-for-merge

#2746 Firefoxでデフォルトのソート順が公表日の降順にならない
  utils/formatTable.ts
Labels: ready-for-merge

#2762 Update translation link in CONTRIBUTION.md
  CONTRIBUTING.md
  docs/en/CONTRIBUTING.md
  docs/es/CONTRIBUTING.md
  docs/fr/CONTRIBUTING.md
  docs/ko/CONTRIBUTING.md
  docs/pt_BR/CONTRIBUTING.md
  docs/th/CONTRIBUTING.md
  docs/zh_TW/CONTRIBUTING.md
Labels: documentation

#2760 ブラウザバックを検知し現在のロケールを言語設定メニューに反映させるように修正
  components/LanguageSelector.vue
Labels: i18n, ready-for-merge

#2763 issue #2718 印刷ページのレイアウト崩れへの対応
  components/flow/FlowPc.vue
  components/flow/FlowPcAdvisory.vue
  components/flow/FlowPcSuspect.vue
  layouts/print.vue
Labels: ready-for-merge

#2798 スマートフォン表示時のSelectorのフォントサイズ変更
  components/LanguageSelector.vue
Labels: ready-for-merge

#2780 [Issue 2587] Add lastUpdate to meta description
  layouts/default.vue
  utils/formatDate.ts
Labels: ready-for-merge

#2749 未翻訳の項目に対しての警告を抑制する
  assets/locales/ja.json
  components/AgencyBarChart.vue
  components/cards/AgencyCard.vue
  components/cards/ConfirmedCasesAttributesCard.vue
  components/cards/MetroCard.vue
Labels: i18n, ready-for-merge

#2759 refs #2757 Make degrees expression consistent
  assets/locales/ja.json
Labels: i18n, ready-for-merge

#2871 「検査陽性者の状況」「検査実施状況」の数値を3桁区切りで表示する
  components/ConfirmedCasesDetailsTable.vue
  components/TestedCasesDetailsTable.vue
Labels: ready-for-merge

#2628 トップページの「やさしい日本語」のルビタグ対応
  components/ConfirmedCasesDetailsTable.vue
  components/DataTable.vue
  components/DataView.vue
  components/DataViewBasicInfoPanel.vue
  components/MapCard.vue
  components/MenuList.vue
  components/SideNavigation.vue
  components/SourceLink.vue
  components/StaticInfo.vue
  components/TI18n.vue
  components/TestedCasesDetailsTable.vue
  components/TimeStackedBarChart.vue
  components/VisitorsBarChart.vue
  components/WhatsNew.vue
  components/cards/AgencyCard.vue
  components/cards/ConfirmedCasesDetailsCard.vue
  components/cards/InspectionPersonsNumberCard.vue
  components/cards/MetroCard.vue
  components/cards/TestedCasesDetailsCard.vue
  components/cards/TestedNumberCard.vue
  pages/index.vue
Labels: i18n

#2425 Hotfix/2386 i18n align browser vers key
  assets/locales/ja.json
  nuxt.config.ts
  pages/about.vue
Labels: i18n, officially-answered

#2846 PC表示時にスクロールできなくなる問題の修正
  layouts/default.vue
Labels: ready-for-merge

#2875 Fix: 2874 Correcting cosmetic minor errors
  pages/about.vue
Labels: ready-for-merge

#2878 ハンバーガーメニューから他のページに遷移した際、ヘッダーの下部に点線が出る問題を修正しました。
  components/SideNavigation.vue
Labels: ready-for-merge

#2879 「都営地下鉄の利用者数の推移」グラフにテキストを追加 #2877
  assets/locales/ja.json
  components/ExternalLink.vue
  components/MetroBarChart.vue
Labels: ready-for-merge

#2881 鹿児島県サイトの URL 変更に追従
  FORKED_SITES.md
Labels: ready-for-merge

#2883 Facebookのアイコン画像を調整
  static/facebook.png
  static/facebook.webp
Labels: ready-for-merge

#2892 香川県・岡山県版サイトのURL更新
  FORKED_SITES.md
Labels: ready-for-merge

#2905 新たな栃木県版ページの追加
  FORKED_SITES.md
Labels: ready-for-merge

#2935 Revert "ハンバーガーメニューから他のページに遷移した際、ヘッダーの下部に点線が出る問題を修正しました。"
  components/SideNavigation.vue
Labels: ready-for-merge

#2903 feat: 「お子様をお持ちの皆様へ」ページへコンテンツの追加・修正 #2886
  assets/locales/ja.json
  pages/parent.vue
Labels: ready-for-merge

#1456 [Bug] お知らせの日本語の日付表記が海外向けになっている
  components/WhatsNew.vue
  utils/formatDate.ts
Labels: i18n

#2948 「都営地下鉄の利用者数の推移」グラフのリンクテキストを修正
  assets/locales/ja.json
  components/MetroBarChart.vue
Labels: ready-for-merge

#2953 Fix 繁體中文 document typo
  docs/zh_TW/README.md
Labels: documentation, ready-for-merge

#2963 「陽性患者の属性」テーブルにて、患者の年代が調査中の場合は「調査中」と表示する
  components/cards/ConfirmedCasesAttributesCard.vue
Labels: ready-for-merge

#2942 「感染症対策本部会議に関すること」の電話番号変更
  pages/contacts.vue
Labels: ready-for-merge

#2965 （再）波線が常に出る問題を解消 #2939 #2940
  components/flow/FlowPcAdvisory.vue
  components/flow/FlowPcSuspect.vue
Labels: ready-for-merge

#2840 nuxt-i18nを6.8.1に更新
  package.json
  yarn.lock
Labels: dependencies, i18n, ready-for-merge

#2936 (再) ja.json の重複キーを除去
  assets/locales/ja.json
Labels: i18n, ready-for-merge

#2977 「東京都緊急事態措置について」のリンクボタンをサイトトップに設置
  assets/variables.scss
  components/WhatsNew.vue
Labels: ready-for-merge

#2967 Add : 「お問い合わせ先一覧」に注意書きを追加.
  assets/locales/ja.json
  pages/contacts.vue
Labels: ready-for-merge

#2681 delete_fbcacheを実行するGithub Actionを追加
  .github/workflows/deploy.yml
Labels: ready-for-merge

#2934 Improvement: 2911 Omitting unused fontawesome CSS
  components/DataView.vue
  nuxt.config.ts
Labels: ready-for-merge

#3013 Add: 「東京都緊急事態措置について」の翻訳キーの追加.
  assets/locales/ja.json
Labels: ready-for-merge

#3020 [ruby] 「やさしいにほんご」を直接開くとローディングが終わらない問題を修正
  components/TI18n.vue
  package.json
  utils/formatTable.ts
  yarn.lock
Labels: i18n

#3056 [ruby] ルビタグ生成処理のクロスブラウザ対応
  components/DataTable.vue
  components/TI18n.vue
  package.json
  utils/formatTable.ts
  yarn.lock
Labels: dependencies, i18n

#2498 グラフの横スクロール
  components/AgencyBarChart.vue
  components/DataView.vue
  components/MetroBarChart.vue
  components/TimeBarChart.vue
  components/TimeStackedBarChart.vue
  components/VisitorsBarChart.vue
  plugins/vue-chart.ts
Labels: officially-approved, ready-for-merge

#2979 「陽性患者の属性」テーブルにて、「10歳未満」を「10代」よりも小さい値としてソートする
  components/DataTable.vue
  components/cards/ConfirmedCasesAttributesCard.vue
Labels: ready-for-merge

#3029 Canvasの代替の隠しテーブルのデータの誤りを修正
  components/AgencyBarChart.vue
  components/MetroBarChart.vue
Labels: ready-for-merge

#3050 ExternalLink の設計を変更
  components/ExternalLink.vue
  components/WhatsNew.vue
Labels: ready-for-merge

#3085 トップページへの遷移時のグラフ横幅初期化不具合の修正
  components/DataView.vue
  components/TimeBarChart.vue
  components/TimeStackedBarChart.vue
  plugins/vue-chart.ts
Labels: ready-for-merge

#3126 [ruby] 「企業の皆様・はたらく皆様へ」のルビタグに対応
  pages/worker.vue
Labels: i18n

#3130 [ruby] 「お子様をお持ちの皆様へ」のルビタグ対応
  pages/parent.vue
Labels: i18n

#3134 [ruby] 新型コロナウイルス感染症が心配なときに（SP）のルビタグ対応
  components/flow/FlowSp.vue
  components/flow/FlowSpAccording.vue
  components/flow/FlowSpAdvisory.vue
  components/flow/FlowSpElder.vue
  components/flow/FlowSpGeneral.vue
  components/flow/FlowSpHospitalized.vue
  components/flow/FlowSpPast.vue
  components/flow/FlowSpSuspect.vue
Labels: i18n

#1767 nuxt-i18n.config.tsに型情報を追加
  nuxt-i18n.config.ts
Labels: assigned, dependencies, i18n, ready-for-merge

#3075 FORKED_SITES.mdに佐賀県版を追加
  FORKED_SITES.md
Labels: ready-for-merge

#3076 #2549 dev-no-axeに対する英訳
  docs/en/README.md
Labels: documentation, ready-for-merge

#3081 READMEにvue-axeについて中国語で翻訳します。
  docs/zh_CN/README.md
Labels: documentation, ready-for-merge

#3093 誤字を修正
  docs/es/README.md
Labels: ready-for-merge

#3097 鳥取県を追加
  FORKED_SITES.md
Labels: ready-for-merge

#3107 pre-commitにx権限を追加。bashであることを明示
  package.json
  pre-commit.sh
Labels: ready-for-merge

#3109 ２系統の時のグラフの色をアップデートする
  utils/colors.ts
Labels: ready-for-merge

#3119 v-data-tableのtbodyの日付セルをthに変更
  components/AgencyBarChart.vue
  components/DataTable.vue
  components/MetroBarChart.vue
  components/TimeBarChart.vue
  components/TimeStackedBarChart.vue
Labels: ready-for-merge

#3144 README.mdから、「開発者向け情報」をFOR_DEVELOPERS.mdに分ける
  FOR_DEVELOPERS.md
  README.md
Labels: documentation, ready-for-merge

#3145 コンポーネントのタグ記法をケバブケースに統一
  components/LanguageSelector.vue
  components/PrinterButton.vue
  components/SideNavigation.vue
  components/flow/FlowSpAccording.vue
  components/flow/FlowSpAdvisory.vue
  components/flow/FlowSpElder.vue
  components/flow/FlowSpGeneral.vue
  components/flow/FlowSpHospitalized.vue
  components/flow/FlowSpPast.vue
  components/flow/FlowSpSuspect.vue
  layouts/default.vue
  layouts/error.vue
  pages/about.vue
  pages/flow.vue
  pages/parent.vue
  pages/worker.vue
Labels: ready-for-merge

#3146 noscriptの時の表示を見やすくしました
  components/NoScript.vue
Labels: ready-for-merge

#3165 八千代市を追加
  FORKED_SITES.md
Labels: ready-for-merge

#3179 「陽性患者の属性」テーブルで使用されている全角ダッシュを翻訳対象から外す
  components/cards/ConfirmedCasesAttributesCard.vue
Labels: ready-for-merge

#3180 FORKED_SITES.mdに市原市を追加
  FORKED_SITES.md
Labels: ready-for-merge

#3200 「陽性患者数」のグラフに注意書きを追加 (hotfix)
  assets/locales/ja.json
  components/cards/ConfirmedCasesNumberCard.vue
Labels: ready-for-merge

#3226 「検査実施件数」、「検査実施状況」のグラフに注意書きを追加
  assets/locales/ja.json
  components/TestedCasesDetailsTable.vue
  components/TimeStackedBarChart.vue
  components/cards/TestedCasesDetailsCard.vue
  components/cards/TestedNumberCard.vue
Labels: ready-for-merge

#2447 スクリーンリーダー向け隠しtableを通常時もアコーディオンで表示
  assets/locales/ja.json
  components/AgencyBarChart.vue
  components/DataTable.vue
  components/DataView.vue
  components/MetroBarChart.vue
  components/TimeBarChart.vue
  components/TimeStackedBarChart.vue
  components/VisitorsBarChart.vue
  components/cards/TestedNumberCard.vue
  nuxt.config.ts
  utils/formatTable.ts
Labels: accessibility, officially-approved, ready-for-merge

#3061 StaticCardコンポーネントの新規ウィンドウ表示アイコンにテキストラベルを追加
  components/ExternalLink.vue
  components/MetroBarChart.vue
  components/StaticCard.vue
  components/WhatsNew.vue
  pages/about.vue
  pages/parent.vue
  pages/worker.vue
Labels: ready-for-merge

#3161 「陽性患者の属性」を遅延レンダー
  components/cards/ConfirmedCasesAttributesCard.vue
Labels: ready-for-merge

#3170 flowページのSP版HTMLの特定箇所を見出し要素に置き換える
  components/flow/FlowSpAccording.vue
  components/flow/FlowSpElder.vue
  components/flow/FlowSpGeneral.vue
  components/flow/FlowSpPast.vue
  components/flow/FlowSpSuspect.vue
  components/flow/flow_sp.scss
Labels: accessibility, ready-for-merge

#3190 「検査実施件数」グラフでの不適切な罫線を削除
  components/TimeStackedBarChart.vue
Labels: ready-for-merge

#3201 「陽性患者数」のグラフに注意書きを追加 (development)
  assets/locales/ja.json
  components/cards/ConfirmedCasesNumberCard.vue
Labels: ready-for-merge

#3215 「100歳以上」に対応する翻訳キーを追加
  assets/locales/ja.json
Labels: ready-for-merge

#3238 「陰性確認」の文言を削除（hotfix分のdevelopment反映用）
  assets/locales/ja.json
  components/cards/TestedNumberCard.vue
Labels: ready-for-merge

#3251 y軸固定グラフ 軸と本体とで suggestedMax は同じ値で固定
  components/TimeStackedBarChart.vue
Labels: ready-for-merge

#3139 [ruby] 新型コロナウイルス感染症が心配なときに（PC） のルビタグ対応
  components/flow/FlowPc.vue
  components/flow/FlowPcAdvisory.vue
  components/flow/FlowPcAdvisory2.vue
  components/flow/FlowPcDays.vue
  components/flow/FlowPcHospitalized.vue
  components/flow/FlowPcNotRequired.vue
  components/flow/FlowPcPcr.vue
  components/flow/FlowPcRequired.vue
  components/flow/FlowPcSuspect.vue
Labels: i18n

#3121 [ruby] 当サイトについて のルビタグ対応
  components/StaticCard.vue
  pages/about.vue
Labels: i18n

#3129 [ruby] /pages/flow.vue のルビタグ対応
  components/PrinterButton.vue
  pages/flow.vue
Labels: i18n

#3135 [ruby]「お問い合わせ先一覧」ページのルビ対応
  pages/contacts.vue
Labels: i18n

#2711 ポルトガル語に翻訳しました
  docs/pt_BR/README.md
Labels: documentation, ready-for-merge

#3105 fix english translation for docs/en/README
  docs/en/README.md
Labels: documentation, ready-for-merge

#3162 韓国語READMEの翻訳(vue-axe)
  docs/ko/README.md
Labels: documentation, ready-for-merge

#3260 茨城県版のサイトのURLを変更しました。
  FORKED_SITES.md
Labels: ready-for-merge

#3276 サイドナビに「新型コロナウイルス感染症に関する東京都の支援策」外部リンクを追加
  assets/locales/ja.json
  components/SideNavigation.vue
Labels: ready-for-merge

#3273 不要になった翻訳キーの除去（2020/04/14）
  assets/locales/ja.json
  components/cards/MetroCard.vue
Labels: i18n, ready-for-merge

#3305 issue #3275 日本語のミスを修正
  components/DataView.vue
Labels: ready-for-merge

#3307 【#3306】福井県版対策サイト公認化による記載の修正
  FORKED_SITES.md
Labels: ready-for-merge

#3281 ja.jsonに追加されていない翻訳キーを追加
  assets/locales/ja.json
Labels: ready-for-merge

#2986 共有ボタンの押せるエリアを広げる
  components/DataView.vue
Labels: ready-for-merge

#3337 「陽性患者数（区市町村別）」の表を追加
  assets/locales/ja.json
  components/ConfirmedCasesByMunicipalitiesTable.vue
  components/DataViewBasicInfoPanel.vue
  components/cards/ConfirmedCasesByMunicipalitiesCard.vue
  nuxt.config.ts
  pages/cards/_card.vue
  pages/index.vue
Labels: officially-approved, ready-for-merge

#3298 [ruby] 当サイトについてのルビタグ生成エラー修正
  components/TI18n.vue
Labels: i18n

#3299 [ruby] 陽性患者の属性 のテーブルのレンダリングでエラー修正
  components/DataTable.vue
Labels: i18n

#3326 「陽性患者の属性」表において、公表日、年代、更に性別と居住地も正しくソートされるように修正する
  components/cards/ConfirmedCasesAttributesCard.vue
Labels: ready-for-merge

#3356 ドキュメント中の netlify.com を netlify.app に置換
  CONTRIBUTING.md
  FORKED_SITES.md
  FOR_DEVELOPERS.md
  docs/en/CONTRIBUTING.md
  docs/en/README.md
  docs/es/CONTRIBUTING.md
  docs/es/README.md
  docs/fr/CONTRIBUTING.md
  docs/fr/README.md
  docs/ko/CONTRIBUTING.md
  docs/ko/README.md
  docs/pt_BR/CONTRIBUTING.md
  docs/pt_BR/README.md
  docs/th/CONTRIBUTING.md
  docs/th/README.md
  docs/vi/CONTRIBUTING.md
  docs/vi/README.md
  docs/zh_CN/CONTRIBUTING.md
  docs/zh_CN/README.md
  docs/zh_TW/CONTRIBUTING.md
  docs/zh_TW/README.md
Labels: documentation, ready-for-merge

#3388 表の英語表記時に適切な位置で改行が行われるように変更
  components/ConfirmedCasesDetailsTable.vue
  components/TestedCasesDetailsTable.vue
Labels: design, i18n, ready-for-merge

#3396 FORKED_SITES.mdの更新
  FORKED_SITES.md
Labels: documentation, ready-for-merge

#3417 [hotfix] 「検査実施状況」「検査実施件数」の注意書きを更新
  assets/locales/ja.json
  components/cards/TestedCasesDetailsCard.vue
  components/cards/TestedNumberCard.vue
Labels: ready-for-merge

#3348 (PR) [/flow][全面改修]ページマークアップ
  pages/flow.vue
  static/flow/responsive/cond_anx.svg
  static/flow/responsive/cond_sy.svg
  static/flow/responsive/cond_sydr.svg
  static/flow/responsive/phone_white.svg
  types/shims-vue.d.ts
Labels: officially-approved, ready-for-merge

#3352 Fix 3021 DataSelector: btn to radio
  components/DataSelector.vue
Labels: accessibility, design, ready-for-merge

#3406 issue #3405 「お子様をお持ちの皆様へ」ページ情報追加
  assets/locales/ja.json
  pages/parent.vue
Labels: officially-approved, ready-for-merge

#3445 群馬県の新型コロナウイルス対策サイトへのリンクを変更
  FORKED_SITES.md
Labels: ready-for-merge

#3448 IE11・Edgeでグラフの「テーブルを表示」を動作させる
  assets/variables.scss
  components/DataView.vue
  components/cards/CardRow.vue
  nuxt.config.ts
  pages/index.vue
  utils/card-event-bus.ts
Labels: officially-approved, ready-for-merge

#3408 issue#3407 「お子様をお持ちの皆様へ」の表記ミス修正
  assets/locales/ja.json
Labels: ready-for-merge

#3459 トップページの検査実施件数の注釈を更新
  assets/locales/ja.json
  components/TimeStackedBarChart.vue
  components/cards/TestedNumberCard.vue
Labels: officially-approved, ready-for-merge

#3473 「検査陽性者の状況」「陽性患者の属性」のテキスト変更・注釈の追加・修正
  assets/locales/ja.json
  components/ConfirmedCasesDetailsTable.vue
  components/DataTable.vue
  components/cards/ConfirmedCasesDetailsCard.vue
Labels: officially-approved, ready-for-merge

#3394 issue#3378 都庁来庁者数グラフのy軸単位
  assets/locales/ja.json
  components/AgencyBarChart.vue
Labels: design, i18n, ready-for-merge

#3458 (PR) [/flow] IE11の表示不具合（イラストsvgがhover時に消える）
  pages/flow.vue
Labels: ready-for-merge

#3481 FORKED_SITES.mdに和歌山県を追加
  FORKED_SITES.md
Labels: ready-for-merge

#3483 Fix #3457: IE11で右側がウィンドウからはみでる
  layouts/default.vue
Labels: ready-for-merge

#3501 「検査実施件数」グラフ下部の注釈のフォントカラー修正
  components/cards/TestedNumberCard.vue
Labels: ready-for-merge

#3449 「陽性患者の属性」表において、無効な日付を取得した場合の動作を修正
  utils/formatTable.ts
Labels: ready-for-merge

#3531 サイドナビに「新型コロナウイルスの感染が判明した方へ」の外部リンクを追加
  assets/locales/ja.json
  components/SideNavigation.vue
Labels: officially-approved, ready-for-merge

#3533 (PR) [/flow]「新型コロナウイルス感染症が心配なときに」ページ内テキスト修正
  pages/flow.vue
Labels: officially-approved, ready-for-merge

#3503 [ruby] #3461 取り込み分へのルビタグ対応
  pages/about.vue
  pages/parent.vue
Labels: i18n

#3460 (PR) [/flow] 4/17版リリース時積み残し対応
  components/flow/FlowPc.vue
  components/flow/FlowPcAdvisory.vue
  components/flow/FlowPcAdvisory2.vue
  components/flow/FlowPcDays.vue
  components/flow/FlowPcHospitalized.vue
  components/flow/FlowPcNotRequired.vue
  components/flow/FlowPcPast.vue
  components/flow/FlowPcPcr.vue
  components/flow/FlowPcRequired.vue
  components/flow/FlowPcSuspect.vue
  components/flow/FlowSp.vue
  components/flow/FlowSpAccording.vue
  components/flow/FlowSpAdvisory.vue
  components/flow/FlowSpElder.vue
  components/flow/FlowSpGeneral.vue
  components/flow/FlowSpHospitalized.vue
  components/flow/FlowSpPast.vue
  components/flow/FlowSpSuspect.vue
  components/flow/flow_sp.scss
  pages/flow.vue
  pages/print/flow.vue
  static/flow/accessibility-24px.svg
  static/flow/accessible-24px.svg
  static/flow/apartment-24px.svg
  static/flow/arrow_downward.svg
  static/flow/arrow_forward-24px.svg
  static/flow/arrow_green.svg
  static/flow/bed.svg
  static/flow/check_circle-24px.svg
  static/flow/cond_anx.svg
  static/flow/cond_sy.svg
  static/flow/cond_sydr.svg
  static/flow/directions_walk-24px.svg
  static/flow/flow_arrow.svg
  static/flow/hotel-24px.svg
  static/flow/house-24px.svg
  static/flow/phone-24px.svg
  static/flow/phone.svg
  static/flow/pregnant_woman-24px.svg
  static/flow/responsive/accessibility.svg
  static/flow/responsive/accessible.svg
  static/flow/responsive/apartment.svg
  static/flow/responsive/arrow_downward.svg
  static/flow/responsive/arrow_forward.svg
  static/flow/responsive/arrow_green.svg
  static/flow/responsive/check_circle.svg
  static/flow/responsive/directions_walk.svg
  static/flow/responsive/flow_arrow.svg
  static/flow/responsive/house.svg
  static/flow/responsive/phone_white.svg
  static/flow/responsive/pregnant_woman.svg
  static/flow/responsive/sentiment_very_dissatisfied.svg
  static/flow/sentiment_very_dissatisfied-24px.svg
Labels: ready-for-merge

#3474 Feature/3472 add tooltip to share button
  assets/locales/ja.json
  components/DataView.vue
Labels: ready-for-merge

#3595 [/flow] 新flowページの文章を翻訳キーとして登録
  assets/locales/ja.json
Labels: i18n

#3464 Fix 3140: Justify Printer Button Content
  components/PrinterButton.vue
Labels: design

#3617 「検査実施状況」チャート・「検査実施件数」グラフの注釈変更
  assets/locales/ja.json
  components/TimeStackedBarChart.vue
  components/cards/TestedCasesDetailsCard.vue
Labels: officially-approved, ready-for-merge

#3635 [hotfix]検査実施件数の注釈を削除
  components/TimeStackedBarChart.vue
Labels: officially-approved, ready-for-merge

#3471 [ruby] トップページ追加分のルビ対応
  assets/global.scss
  components/AgencyBarChart.vue
  components/ConfirmedCasesByMunicipalitiesTable.vue
  components/DataView.vue
  components/MetroBarChart.vue
  components/TimeBarChart.vue
  components/TimeStackedBarChart.vue
  components/WhatsNew.vue
  components/cards/ConfirmedCasesByMunicipalitiesCard.vue
  components/cards/ConfirmedCasesNumberCard.vue
Labels: i18n

#3468 [ruby] /flow のルビタグ対応
  pages/flow.vue
Labels: i18n, need-i18n

#3609 [ruby] TI18n コンポーネントの正規表現改善
  utils/ruby.ts
Labels: i18n

#3695 [/flow] 「新型コロナコールセンター」の文言変更 #3676
  assets/locales/ja.json
  pages/flow.vue
Labels: i18n

#3508 FORKED_SITES.mdに全国版を追加
  FORKED_SITES.md
Labels: documentation, ready-for-merge

#3589 yarn dev コマンドの実行パフォーマンスを改善する
  package.json
  plugins/axe.ts
  yarn.lock
Labels: accessibility, dependencies, ready-for-merge

#3594 add i18n generator
  .github/workflows/i18n_generator.yml
  auto-i18n/i18n_generator.py
Labels: i18n, ready-for-merge

#3666 add Shizuoka city to FORKED_SITES.md
  FORKED_SITES.md
Labels: documentation, ready-for-merge

#3669 Add contributors (2020-04-25)
  CONTRIBUTORS.md
Labels: documentation, ready-for-merge

#3674 グラフの埋め込み用コードをコピーした際に表示される文字を非表示に修正。
  components/DataView.vue
Labels: ready-for-merge

#3677 未使用のメソッド `getAdjustX` を削除
  components/ConfirmedCasesDetailsTable.vue
  components/TestedCasesDetailsTable.vue
Labels: ready-for-merge

#3678 「東京都緊急事態措置について」のボタンのクリック領域が狭い問題の修正
  components/WhatsNew.vue
Labels: ready-for-merge

#3690 fix: #3688 カードの共有ボタンから表示するSNSボタンのズレを修正（再）
  components/DataView.vue
Labels: ready-for-merge

#3693 FORKED_SITES.mdに横浜市を追加
  FORKED_SITES.md
Labels: documentation, ready-for-merge

#3671 「都営地下鉄の利用者数の推移」グラフに外部リンクを追加
  assets/locales/ja.json
  components/MetroBarChart.vue
Labels: officially-approved, ready-for-merge

#3741 hotfix: 「検査陽性者の状況」チャートに注釈を追加 #3737
  components/cards/ConfirmedCasesDetailsCard.vue
Labels: officially-approved, ready-for-merge

#3742 hotfix: 「検査陽性者の状況」チャートに注釈を追加 #3737
  components/cards/ConfirmedCasesDetailsCard.vue
Labels: hotfix, officially-approved

#3639 #2837 add copyright mark
  components/SideNavigation.vue
Labels: ready-for-merge

#3673 fix: グラフのテーブル でデータを日付の降順でソートする
  components/AgencyBarChart.vue
  components/MetroBarChart.vue
Labels: ready-for-merge

#3699 refs #3322 日本語のFOR_DEVELOPERS.mdの記載を修正する
  FOR_DEVELOPERS.md
Labels: documentation, ready-for-merge

#3701 refs #3322 英語のREADME.mdから、「開発者向け情報」を別ファイルに分ける
  docs/en/FOR_DEVELOPERS.md
  docs/en/README.md
Labels: documentation, ready-for-merge

#3702 refs #3322 スペイン語のREADME.mdから、「開発者向け情報」を別ファイルに分ける
  docs/es/FOR_DEVELOPERS.md
  docs/es/README.md
Labels: documentation, ready-for-merge

#3705 refs #3322 フランス語のREADME.mdから、「開発者向け情報」を別ファイルに分ける
  docs/fr/FOR_DEVELOPERS.md
  docs/fr/README.md
Labels: documentation, ready-for-merge

#3713 refs #3322 韓国語のREADME.mdから、「開発者向け情報」を別ファイルに分ける
  docs/ko/FOR_DEVELOPERS.md
  docs/ko/README.md
Labels: documentation, ready-for-merge

#3714 refs #3322 ポルトガル語のREADME.mdから、「開発者向け情報」を別ファイルに分ける
  docs/pt_BR/FOR_DEVELOPERS.md
  docs/pt_BR/README.md
Labels: documentation, ready-for-merge

#3715 refs #3322 タイ語のREADME.mdから、「開発者向け情報」を別ファイルに分ける
  docs/th/FOR_DEVELOPERS.md
  docs/th/README.md
Labels: documentation, ready-for-merge

#3716 refs #3322 ベトナム語のREADME.mdから、「開発者向け情報」を別ファイルに分ける
  docs/vi/FOR_DEVELOPERS.md
  docs/vi/README.md
Labels: documentation, ready-for-merge

#3720 refs #3322 中国語(簡体字)のREADME.mdから、「開発者向け情報」を別ファイルに分ける
  docs/zh_CN/FOR_DEVELOPERS.md
  docs/zh_CN/README.md
Labels: documentation, ready-for-merge

#3721 refs #3322 中国語(繁体字)のREADME.mdから、「開発者向け情報」を別ファイルに分ける
  docs/zh_TW/FOR_DEVELOPERS.md
  docs/zh_TW/README.md
Labels: documentation, ready-for-merge

#3739 Firefoxで「東京都緊急事態措置について」のボタンの外部リンクアイコンがずれてしまう問題の修正
  components/WhatsNew.vue
Labels: ready-for-merge

#3743 ナビゲーションに「ご家庭でのマスク等の捨て方」・「東京都における滞在人口の増減」を追加
  components/MenuList.vue
  components/SideNavigation.vue
  static/masktrash.svg
Labels: officially-approved, ready-for-merge

#3762 FORKED_SITES.mdに記載されている横浜市版のGitHubプロジェクト名を変更
  FORKED_SITES.md
Labels: ready-for-merge

#3138 sidebarのsocial一覧にyoutubeリンクの追加
  components/SideNavigation.vue
  static/youtube.png
  static/youtube.webp
Labels: officially-answered, officially-approved, ready-for-merge

#3784 fix i18n generator action issue
  .github/workflows/i18n_generator.yml
Labels: ready-for-merge
