Repository tokyo-metropolitan-gov/covid19, pull requests merged in 2020-10, with the labels that each got.

#5443 Re-renovate Autoprefixer (included in Nuxt.js)
  components/cards/CardRow.vue
  nuxt.config.ts
  package.json
  yarn.lock
Labels: ready-for-merge

#5497 @fullhuman/postcss-purgecssのメジャーアップデートに対するマイグレーション
  nuxt.config.ts
  package.json
  yarn.lock
Labels: ready-for-merge

#5512 ja.json から一度 "新型コロナウイルス感染症が心配なときに" のエントリを削除
  assets/locales/ja.json
Labels: i18n

#5506 未使用ライブラリをremove
  package.json
  yarn.lock
Labels: ready-for-merge

#5505 「企業の皆様・はたらく皆様へ」コンテンツ差し替え
  pages/worker.vue
Labels: officially-approved, ready-for-merge

#5551 サイドナビによくあるご質問の外部リンクを追加
  components/MenuList.vue
  components/SideNavigation.vue
  static/support.svg
Labels: officially-approved, ready-for-merge

#5549 総括コメントをmonitoring_items.jsonから読み込むように修正
  components/MonitoringCommentCard.vue
  components/cards/MonitoringItemsOverviewCard.vue
  utils/formatMonitoringItems.ts
Labels: officially-approved, ready-for-merge

#5293 陽性患者の属性をオープンデータのAPIに切り替え
  components/DataTable.vue
  components/DataView.vue
  components/cards/ConfirmedCasesAttributesCard.vue
  pages/cards/_card.vue
  utils/formatTable.ts
Labels: officially-approved, ready-for-merge

#5627 flowへのリンクを暫定的に福祉保健局のURLに変更
  components/SideNavigation.vue
  components/SiteTopUpper.vue
Labels: officially-approved, ready-for-merge
