Repository tokyo-metropolitan-gov/covid19, pull requests merged in 2021-09, with the labels that each got.

#6705 サイトリニューアルリリース後の指摘事項を修正
  components/_shared/SideNavigation.vue
  components/index/CardsFeatured/ConfirmedCasesNumber/Card.vue
  components/index/CardsFeatured/InfectionMedicalCareProvisionStatus/Card.vue
  components/index/CardsFeatured/TestedNumber/Card.vue
  components/index/CardsFeatured/Vaccination/Card.vue
  components/index/_shared/CardRow.vue
Labels: ready-for-merge, officially-approved

#6721 import/namedのeslintエラーを一旦コメントで回避
  components/index/CardsMonitoring/HospitalizedNumber/Chart.vue
  components/index/CardsMonitoring/MonitoringConfirmedCasesNumber/Chart.vue
  components/index/CardsMonitoring/MonitoringItemsOverview/Table/InfectionStatus.vue
  components/index/CardsMonitoring/MonitoringItemsOverview/Table/MedicalSystem.vue
  components/index/CardsMonitoring/MonitoringItemsOverview/Table/ValueWithTranslatableUnit.vue
  components/index/CardsReference/Agency/Chart.vue
  components/index/CardsReference/MonitoringConsultationDeskReportsNumber/Chart.vue
  components/index/_shared/DataViewTable.vue
  components/index/_shared/MixedBarAndLineChart.vue
  components/index/_shared/ScrollableChart.vue
  layouts/default.vue
  layouts/print.vue
  pages/about.vue
  pages/contacts.vue
  pages/index.vue
  pages/parent.vue
  pages/worker.vue
  plugins/vue-chart.ts
  utils/i18nUtils.ts
Labels: ready-for-merge

#6719 スクロールによるタブ表示の判定部分を削除
  pages/index.vue
  pages/monitoring.vue
  pages/reference.vue
Labels: ready-for-merge

#6735 モニタリング項目(4)陽性率のツールチップ内の単位を「%」に修正
  components/index/CardsMonitoring/PositiveRate/Chart.vue
Labels: ready-for-merge, officially-approved

#6730 「報告日別による陽性者数（65歳以上）の推移」グラフカードを実装
  components/index/CardsReference.vue
  components/index/CardsReference/PositiveNumberOver65/Card.vue
  libraries/auto_generated/data_converter/convertPositiveOver65.ts
  libraries/repositories/PositiveOver65Repository.ts
  nuxt.config.ts
  pages/cards/_card.vue
  store/index.ts
  ui-test/ogp_screenshot.py
Labels: ready-for-merge, officially-approved

#6769 refactor: fix eslint error import/named
  components/_shared/SideNavigation.vue
  components/_shared/SideNavigation/MenuList.vue
  components/_shared/SideNavigation/MenuListContents.vue
  components/index/CardsFeatured/InfectionMedicalCareProvisionStatus/Table/InfectionStatus.vue
  components/index/CardsFeatured/InfectionMedicalCareProvisionStatus/Table/MedicalSystem.vue
  components/index/CardsFeatured/TestedNumber/Chart.vue
  components/index/CardsFeatured/TokyoFeverConsultationCenterReportsNumber/Chart.vue
  components/index/CardsFeatured/Vaccination/Chart.vue
  components/index/CardsMonitoring/HospitalizedNumber/Chart.vue
  components/index/CardsMonitoring/MonitoringConfirmedCasesNumber/Chart.vue
  components/index/CardsMonitoring/MonitoringItemsOverview/Table/InfectionStatus.vue
  components/index/CardsMonitoring/MonitoringItemsOverview/Table/MedicalSystem.vue
  components/index/CardsMonitoring/MonitoringItemsOverview/Table/ValueWithTranslatableUnit.vue
  components/index/CardsMonitoring/PositiveRate/Chart.vue
  components/index/CardsMonitoring/UntrackedRate/Chart.vue
  components/index/CardsReference/Agency/Chart.vue
  components/index/CardsReference/MonitoringConsultationDeskReportsNumber/Chart.vue
  components/index/CardsReference/Variant/Chart.vue
  components/index/_shared/DataView.vue
  components/index/_shared/DataViewTable.vue
  components/index/_shared/MixedBarAndLineChart.vue
  components/index/_shared/ScrollableChart.vue
  layouts/print.vue
  pages/about.vue
  pages/contacts.vue
  pages/index.vue
  pages/monitoring.vue
  pages/parent.vue
  pages/reference.vue
  pages/worker.vue
  plugins/vue-chart.ts
  utils/i18nUtils.ts
Labels: ready-for-merge

#6767 fix: flicker on switching tabs
  app/router.scrollBehavior.js
  components/index/CardsTab.vue
  tsconfig.json
Labels: ready-for-merge

#6774 style: show outline on focus
  components/index/CardsReference/ConfirmedCasesAttributes/DataTable.vue
  components/index/CardsReference/ConfirmedCasesByMunicipalities/Table.vue
  components/index/_shared/DataViewTable.vue
  components/index/_shared/ScrollableChart.vue
Labels: ready-for-merge, accessibility

#6773 陽性者の属性テーブルのセレクトボックスとページネーションをカスタムで作成
  components/index/CardsReference/ConfirmedCasesAttributes/DataTable.vue
Labels: ready-for-merge, accessibility

#6772 スマホ幅メニューのWAI-ARIA指定を修正
  components/_shared/SideNavigation.vue
Labels: ready-for-merge, accessibility

#6771 グラフ目盛りのfontColorを#808080から#707070に変更
  components/index/CardsFeatured/TestedNumber/Chart.vue
  components/index/CardsFeatured/TokyoFeverConsultationCenterReportsNumber/Chart.vue
  components/index/CardsFeatured/Vaccination/Chart.vue
  components/index/CardsMonitoring/HospitalizedNumber/Chart.vue
  components/index/CardsMonitoring/MonitoringConfirmedCasesNumber/Chart.vue
  components/index/CardsMonitoring/PositiveRate/Chart.vue
  components/index/CardsMonitoring/SevereCase/Chart.vue
  components/index/CardsMonitoring/UntrackedRate/Chart.vue
  components/index/CardsReference/Agency/Chart.vue
  components/index/CardsReference/Metro/Chart.vue
  components/index/CardsReference/MonitoringConsultationDeskReportsNumber/Chart.vue
  components/index/CardsReference/Variant/Chart.vue
  components/index/_shared/MixedBarAndLineChart.vue
  components/index/_shared/TimeBarChart.vue
Labels: ready-for-merge, accessibility

#6770 HTMLの文法違反を修正
  components/_shared/SideNavigation.vue
  components/_shared/SideNavigation/MenuList.vue
  components/index/CardsFeatured/TestedNumber/Chart.vue
  components/index/CardsFeatured/TokyoFeverConsultationCenterReportsNumber/Chart.vue
  components/index/CardsFeatured/Vaccination/Chart.vue
  components/index/CardsMonitoring/MonitoringConfirmedCasesNumber/Chart.vue
  components/index/CardsMonitoring/PositiveRate/Chart.vue
  components/index/CardsMonitoring/UntrackedRate/Chart.vue
  components/index/CardsReference/Agency/Chart.vue
  components/index/CardsReference/ConfirmedCasesAttributes/DataTable.vue
  components/index/CardsReference/Metro/Chart.vue
  components/index/CardsReference/MonitoringConsultationDeskReportsNumber/Chart.vue
  components/index/CardsReference/Variant/Chart.vue
  components/index/_shared/CardsLazyRow.vue
  components/index/_shared/DataView/ExpantionPanel.vue
  components/index/_shared/MixedBarAndLineChart.vue
  nuxt.config.ts
Labels: ready-for-merge, accessibility

#6779 Revert "style: show outline on focus"
  components/index/CardsReference/ConfirmedCasesAttributes/DataTable.vue
  components/index/CardsReference/ConfirmedCasesByMunicipalities/Table.vue
  components/index/_shared/DataViewTable.vue
  components/index/_shared/ScrollableChart.vue
Labels: ready-for-merge

#6786 style: show outline on focus graph
  components/index/_shared/ScrollableChart.vue
Labels: ready-for-merge, accessibility

#6785 style: show outline on focus tables
  components/index/CardsReference/ConfirmedCasesAttributes/DataTable.vue
  components/index/CardsReference/ConfirmedCasesByMunicipalities/Table.vue
  components/index/_shared/DataViewTable.vue
Labels: ready-for-merge, accessibility

#6784 custom-expansion-panelコンポーネントを作成
  components/_shared/CustomExpansionPanel.vue
  components/_shared/SideNavigation/MenuList.vue
  components/index/_shared/CardRow.vue
  components/index/_shared/CardsLazyRow.vue
  components/index/_shared/DataView.vue
  components/index/_shared/DataView/ExpantionPanel.vue
Labels: ready-for-merge, accessibility

#6783 タブのroleとaria-selectedを外すように修正
  components/index/CardsTab.vue
Labels: ready-for-merge, accessibility

#6782 ラベルのないsticky-chartのcanvasにaria-hiddenを付与する
  components/index/CardsFeatured/TestedNumber/Chart.vue
  components/index/CardsFeatured/TokyoFeverConsultationCenterReportsNumber/Chart.vue
  components/index/CardsFeatured/Vaccination/Chart.vue
  components/index/CardsMonitoring/HospitalizedNumber/Chart.vue
  components/index/CardsMonitoring/MonitoringConfirmedCasesNumber/Chart.vue
  components/index/CardsMonitoring/PositiveRate/Chart.vue
  components/index/CardsMonitoring/SevereCase/Chart.vue
  components/index/CardsMonitoring/UntrackedRate/Chart.vue
  components/index/CardsReference/Agency/Chart.vue
  components/index/CardsReference/Metro/Chart.vue
  components/index/CardsReference/MonitoringConsultationDeskReportsNumber/Chart.vue
  components/index/CardsReference/Variant/Chart.vue
  components/index/_shared/MixedBarAndLineChart.vue
  components/index/_shared/TimeBarChart.vue
Labels: ready-for-merge, accessibility

#6777 注釈の折り畳みボタンのアクセシビリティ改善
  components/index/_shared/DataView.vue
Labels: ready-for-merge, accessibility

#6795 「企業の皆様・はたらく皆様へ」ページのコンテンツ修正
  pages/worker.vue
Labels: ready-for-merge, officially-approved

#6551 サイトマップページを追加
  assets/json/cardRoutesSettings.json
  components/_shared/SideNavigation.vue
  components/_shared/StaticCard.vue
  nuxt.config.ts
  pages/cards/_card.vue
  pages/sitemap.vue
  types/cardRoutesSettings.ts
  ui-test/ogp_screenshot.py
Labels: ready-for-merge, officially-approved

#6793 グラフのカラー見直し
  assets/variables.scss
  components/index/CardsMonitoring/PositiveRate/Chart.vue
  components/index/CardsMonitoring/UntrackedRate/Chart.vue
  components/index/CardsReference/Metro/Chart.vue
  components/index/_shared/DataView.vue
  components/index/_shared/MixedBarAndLineChart.vue
  utils/colors.ts
Labels: ready-for-merge

#6801 都営地下鉄グラフのpoint styleを変更
  components/index/CardsReference/Metro/Chart.vue
  components/index/CardsReference/Variant/Chart.vue
Labels: ready-for-merge, officially-approved

#6819 シェアのbutton要素にaria-haspopup="true"とaria-expandedを付与
  components/index/_shared/DataView/Share.vue
Labels: ready-for-merge, accessibility

#6807 病床数の単位を英語では付与しない
  components/index/CardsFeatured/InfectionMedicalCareProvisionStatus/Table/MedicalSystem.vue
Labels: ready-for-merge

#6811 Translatable Unitをi18n generatorで検出可能にする
  auto-i18n/i18n_generator.py
Labels: ready-for-merge

#6818 legendのbutton要素にrole="checkbox"とaria-checkedを付与
  components/index/CardsFeatured/TestedNumber/Chart.vue
  components/index/CardsFeatured/TokyoFeverConsultationCenterReportsNumber/Chart.vue
  components/index/CardsFeatured/Vaccination/Chart.vue
  components/index/CardsMonitoring/MonitoringConfirmedCasesNumber/Chart.vue
  components/index/CardsMonitoring/PositiveRate/Chart.vue
  components/index/CardsMonitoring/UntrackedRate/Chart.vue
  components/index/CardsReference/Agency/Chart.vue
  components/index/CardsReference/Metro/Chart.vue
  components/index/CardsReference/MonitoringConsultationDeskReportsNumber/Chart.vue
  components/index/CardsReference/Variant/Chart.vue
  components/index/_shared/MixedBarAndLineChart.vue
Labels: ready-for-merge, accessibility

#6823 ウェブアクセシビリティ試験結果のページを作成
  pages/about.vue
  pages/accessibility-results.vue
  pages/sitemap.vue
Labels: ready-for-merge, accessibility, officially-approved
