Repository tokyo-metropolitan-gov/covid19, pull requests merged in 2021-08, with the labels that each got.

#6561 英語の月の表記を短縮形にする
  nuxt-i18n.config.ts
Labels: officially-approved, ready-for-merge

#6580 「検査陽性者の状況」カードに注釈を追加
  components/index/CardsMonitoring/ConfirmedCasesDetails/Card.vue
Labels: officially-approved, ready-for-merge

#6589 parentのページタイトルを修正
  pages/parent.vue
Labels: ready-for-merge, officially-approved

#6533 cardのタイトル部のマークアップを修正
  components/index/_shared/DataViewDataSetPanel.vue
Labels: ready-for-merge, officially-approved

#6129 「緊急事態宣言中の都内の滞在人口の増減状況」の地名の中国語表記を変更する
  components/index/SiteTopUpper/StayingPopulation.vue
Labels: ready-for-merge, officially-approved

#6528 cardの個別ページにh2タイトルを追加
  pages/cards/_card.vue
Labels: ready-for-merge, officially-approved

#6601 「変異株情報」ボタンを「自宅での療養」ボタンに差し替え
  assets/variables.scss
  components/_shared/AppLink.vue
  components/index/SiteTopUpper/WhatsNew.vue
Labels: ready-for-merge, officially-approved

#6607 「専門家による分析・総括コメントの詳細はこちら」のURLを更新
  components/index/CardsMonitoring/MonitoringItemsOverview/Card.vue
  components/index/SiteTopUpper/MonitoringComment/Card.vue
Labels: ready-for-merge

#6661 ボタン/タブhover時のアイコンの視覚性を改善
  components/index/CardsTab.vue
  components/index/SiteTopUpper/WhatsNew.vue
Labels: ready-for-merge

#6666 タブ毎にパーマリンクでアクセスできるように修正
  app/router.scrollBehavior.js
  components/index/CardsTab.vue
  nuxt.config.ts
  pages/reference.vue
Labels: ready-for-merge

#6614 「相談の手順を見る 」のコーナーを「新型コロナ保健医療情報ポータル」に変更
  components/index/SiteTopUpper/Consultation.vue
  components/index/SiteTopUpper/Consultation/StaticInfo.vue
Labels: ready-for-merge, officially-approved, release-schedule-available

#6615 前日比表示の単位を％からポイントに変更
  components/index/CardsMonitoring/PositiveRate/Card.vue
  components/index/CardsMonitoring/PositiveRate/Chart.vue
  components/index/CardsMonitoring/UntrackedRate/Card.vue
  components/index/CardsMonitoring/UntrackedRate/Chart.vue
Labels: ready-for-merge, officially-approved, release-schedule-available

#6616 「モニタリング項目」に「国のステージ判断のための指標」のボタンリンクを追加
  components/index/CardsMonitoring/MonitoringItemsOverview/Card.vue
Labels: ready-for-merge, officially-approved, release-schedule-available

#6675 都内の滞在人口の増減状況のリデザイン
  components/index/SiteTopUpper/StayingPopulation.vue
Labels: ready-for-merge, officially-approved, release-schedule-available

#6686 「L452R変異株スクリーニングの実施状況」グラフ下に「変異株情報」ボタンを追加
  components/index/CardsReference/Variant/Card.vue
  components/index/CardsReference/Variant/Chart.vue
Labels: ready-for-merge, officially-approved, release-schedule-available

#6689 「検査実施件数」グラフ下に「検査情報」ボタンを追加・「ワクチン接種数（累計）」グラフ下に「ワクチン情報」ボタンを追加
  components/index/CardsReference/TestedNumber/Card.vue
  components/index/CardsReference/TestedNumber/Chart.vue
  components/index/CardsReference/Vaccination/Card.vue
  components/index/CardsReference/Vaccination/Chart.vue
  components/index/SiteTopUpper/WhatsNew.vue
Labels: ready-for-merge, officially-approved, release-schedule-available

#6692 注釈の折りたたみをline-clampを使わない方法で修正
  components/index/_shared/DataView.vue
Labels: ready-for-merge, officially-approved, release-schedule-available

#6534 サイドナビの区切りブロックのマークアップを修正
  components/_shared/SideNavigation.vue
  components/_shared/SideNavigation/MenuList.vue
  components/_shared/SideNavigation/MenuListContents.vue
Labels: ready-for-merge, officially-approved, release-schedule-available

#6685 サイトトップを３タブ化
  assets/locales/zh_TW.json
  components/index/CardsFeatured.vue
  components/index/CardsFeatured/ConfirmedCasesDetails/Card.vue
  components/index/CardsFeatured/ConfirmedCasesDetails/Table.vue
  components/index/CardsFeatured/ConfirmedCasesNumber/Card.vue
  components/index/CardsFeatured/InfectionMedicalCareProvisionStatus/Card.vue
  components/index/CardsFeatured/InfectionMedicalCareProvisionStatus/Table/InfectionStatus.vue
  components/index/CardsFeatured/InfectionMedicalCareProvisionStatus/Table/MedicalSystem.vue
  components/index/CardsFeatured/MonitoringComment/Card.vue
  components/index/CardsFeatured/MonitoringComment/Frame.vue
  components/index/CardsFeatured/MonitoringComment/RandomImage.vue
  components/index/CardsFeatured/TelephoneAdvisoryReportsNumber/Card.vue
  components/index/CardsFeatured/TestedNumber/Card.vue
  components/index/CardsFeatured/TestedNumber/Chart.vue
  components/index/CardsFeatured/TokyoFeverConsultationCenterReportsNumber/Card.vue
  components/index/CardsFeatured/TokyoFeverConsultationCenterReportsNumber/Chart.vue
  components/index/CardsFeatured/Vaccination/Card.vue
  components/index/CardsFeatured/Vaccination/Chart.vue
  components/index/CardsMonitoring.vue
  components/index/CardsMonitoring/MonitoringItemsOverview/Card.vue
  components/index/CardsMonitoring/PositiveRate/Chart.vue
  components/index/CardsMonitoring/UntrackedRate/Chart.vue
  components/index/CardsReference.vue
  components/index/CardsTab.vue
  components/index/SiteTopUpper.vue
  components/index/SiteTopUpper/InfectionMedicalCareProvisionStatus.vue
  components/index/SiteTopUpper/MonitoringComment/Card.vue
  components/index/SiteTopUpper/MonitoringComment/ImageSwipe.vue
  components/index/_shared/CardsLazyRow.vue
  components/index/_shared/DataView.vue
  nuxt.config.ts
  pages/cards/_card.vue
  pages/monitoring.vue
  ui-test/ogp_screenshot.py
Labels: ready-for-merge, officially-approved, release-schedule-available
