Repository tokyo-metropolitan-gov/covid19, pull requests merged in 2022-01, with the labels that each got.

#7032 CONTRIBUTORS.md の更新 (2022-01-04)
  CONTRIBUTORS.md
Labels: ready-for-merge

#7035 Fix 2964:英語のメニューリンクをホバーまたは押したときに文字幅が変わってしまう問題を修正
  components/_shared/SideNavigation/MenuListContents.vue
Labels: ready-for-merge

#7057 本日のサマリを２分割、ワクチン接種状況を追加
  assets/json/cardRoutesSettings.json
  components/index/CardsFeatured.vue
  components/index/CardsFeatured/InfectionSummary/Card.vue
  components/index/CardsFeatured/InfectionSummary/Frame.vue
  components/index/CardsFeatured/InfectionSummary/Table/InfectionStatus.vue
  components/index/CardsFeatured/InfectionSummary/Table/VaccinationStatus.vue
  components/index/CardsFeatured/MedicalCareSummary/Card.vue
  components/index/CardsFeatured/MedicalCareSummary/Frame.vue
  components/index/CardsFeatured/MedicalCareSummary/Table/MedicalSystem.vue
  components/index/_shared/DataView.vue
  data/infection_medicalcare_summary.json
  data/infection_medicalcareprovision_status.json
  libraries/auto_generated/data_converter/convertInfectionMedicalcareSummary.ts
  pages/cards/_card.vue
  tool/generateDataConverters.ts
Labels: ready-for-merge, officially-approved, release-schedule-available

#7029 グラフに日付範囲フィルターを実装
  components/index/CardsFeatured/TestedNumber/Chart.vue
  components/index/CardsFeatured/TokyoFeverConsultationCenterReportsNumber/Chart.vue
  components/index/CardsFeatured/Vaccination/Card.vue
  components/index/CardsFeatured/Vaccination/Chart.vue
  components/index/CardsMonitoring/HospitalizedNumber/Chart.vue
  components/index/CardsMonitoring/MonitoringConfirmedCasesNumber/Chart.vue
  components/index/CardsMonitoring/PositiveRate/Chart.vue
  components/index/CardsMonitoring/SevereCase/Chart.vue
  components/index/CardsMonitoring/UntrackedRate/Chart.vue
  components/index/_shared/DateRangeSlider.vue
  components/index/_shared/MixedBarAndLineChart.vue
  components/index/_shared/TimeBarChart.vue
  plugins/vue-chart.ts
Labels: ready-for-merge, officially-approved
