Repository tokyo-metropolitan-gov/covid19, pull requests merged in 2022-09, with the labels that each got.

#7477 不要な `aria-label` を削除
  components/index/CardsFeatured/ConfirmedCasesDetails/Card.vue
  components/index/CardsFeatured/InfectionSummary/Card.vue
  components/index/CardsFeatured/MedicalCareSummary/Card.vue
Labels: ready-for-merge, preview-deploy

#7479 日付スライダーのthumb付近に実際の日付を表示する
  components/index/_shared/DateRangeSlider.vue
Labels: ready-for-merge, preview-deploy

#7488 Safari16で線が細くポイントに白丸がレンダリングされる事への対応
  components/index/CardsFeatured/TokyoFeverConsultationCenterReportsNumber/Chart.vue
  components/index/CardsFeatured/Vaccination/Chart.vue
  components/index/CardsMonitoring/MonitoringConfirmedCasesNumber/Chart.vue
  components/index/CardsMonitoring/PositiveRate/Chart.vue
  components/index/CardsMonitoring/UntrackedRate/Chart.vue
  components/index/CardsReference/Metro/Chart.vue
  components/index/_shared/MixedBarAndLineChart.vue
Labels: ready-for-merge, preview-deploy

#7490 rspec のテストコードをリニューアル後の挙動に追いつく
  spec/feature/index_CardsFeatured_h3_spec.rb
  spec/feature/index_CardsReference_DataViewExpantionPanel_spec.rb
  spec/feature/index_CardsReference_h3_spec.rb
  spec/feature/index_SiteTopUpper_h3_spec.rb
  spec/spec_helper.rb
Labels: ready-for-merge

#7499 `::v-deep` に関する警告が出力されないようにする
  components/_shared/SideNavigation/MenuListContents.vue
  pages/sitemap.vue
Labels: ready-for-merge, preview-deploy

#7500 「報告日別による陽性者数の推移」グラフのデータ元をdata.jsonからdaily_positive_detail.jsonに差し替え
  components/index/CardsFeatured/ConfirmedCasesNumber/Card.vue
Labels: ready-for-merge, officially-approved, preview-deploy

#7519 Fix Issue-7509
  components/index/CardsMonitoring/MonitoringItemsOverview/Card.vue
  components/index/CardsMonitoring/MonitoringItemsOverview/Table/InfectionStatus.vue
  components/index/CardsMonitoring/MonitoringItemsOverview/Table/MedicalSystem.vue
Labels: ready-for-merge, officially-approved, release-schedule-available

#7517 Fix Issue-7510
  assets/json/cardRoutesSettings.json
  components/index/CardsMonitoring.vue
  components/index/CardsMonitoring/HospitalizedNumber/Card.vue
  components/index/CardsMonitoring/MonitoringConfirmedCasesNumber/Card.vue
  components/index/CardsMonitoring/PositiveRate/Card.vue
  components/index/CardsMonitoring/SevereCase/Card.vue
  components/index/CardsMonitoring/TokyoRulesApplicationNumber/Card.vue
  components/index/CardsMonitoring/UntrackedRate/Card.vue
  components/index/CardsMonitoring/UntrackedRate/Chart.vue
  components/index/CardsMonitoring/UntrackedRate/DataViewDataSetPanel.vue
  components/index/_shared/DataView.vue
  libraries/repositories/DailyPositiveDetailRepository.ts
  libraries/repositories/PositiveRateRepository.ts
  libraries/repositories/PositiveStatusRepository.ts
  libraries/repositories/TokyoRuleRepository.ts
  pages/cards/_card.vue
  spec/feature/index_CardsMonitoring_h3_spec.rb
Labels: ready-for-merge, officially-approved, release-schedule-available

#7516 Fix Issue-7511
  components/index/CardsFeatured/ConfirmedCasesNumber/Card.vue
  components/index/CardsReference/ConfirmedCasesAttributes/Card.vue
  components/index/CardsReference/ConfirmedCasesAttributes/DataTable.vue
  components/index/CardsReference/ConfirmedCasesByMunicipalities/Card.vue
  components/index/CardsReference/ConfirmedCasesByMunicipalities/Table.vue
  components/index/CardsReference/PositiveNumberByDevelopedDate/Card.vue
  components/index/CardsReference/PositiveNumberByDiagnosedDate/Card.vue
  components/index/CardsReference/PositiveNumberOver65/Card.vue
Labels: ready-for-merge, officially-approved, release-schedule-available

#7513 [全数届出見直しに伴う改修]患者の発生状況等
  components/index/CardsFeatured/InfectionSummary/Card.vue
  components/index/CardsFeatured/InfectionSummary/Table/InfectionStatus.vue
  components/index/CardsFeatured/InfectionSummary/Table/VaccinationStatus.vue
Labels: ready-for-merge, officially-approved, release-schedule-available

#7512 Fix Issue-7508
  components/index/CardsFeatured/ConfirmedCasesDetails/Card.vue
  components/index/CardsFeatured/ConfirmedCasesDetails/Table.vue
Labels: ready-for-merge, officially-approved, release-schedule-available

#7476 iOS VoiceOver時に@changeのみ発火するためv-bindに変更
  components/index/_shared/DateRangeSlider.vue
Labels: ready-for-merge

#7526 患者の発生状況等のお知らせテキスト修正
  components/index/CardsFeatured/InfectionSummary/Card.vue
Labels: ready-for-merge

#7536 [hotfix]yarn generate-data-converters
  libraries/auto_generated/data_converter/convertData.ts
  libraries/auto_generated/data_converter/convertInfectionMedicalcareSummary.ts
  libraries/auto_generated/data_converter/convertMonitoringItems.ts
  libraries/auto_generated/data_converter/convertVaccinationCount.ts
  libraries/auto_generated/data_converter/convertVariants.ts
Labels: preview-deploy

#7540 ウェブアクセシビリティ試験結果ページに2022年度分を追記
  nuxt.config.ts
  pages/about.vue
  pages/accessibility-results.vue
  pages/sitemap.vue
  plugins/vue-scrollto.ts
Labels: ready-for-merge, preview-deploy
