Repository tokyo-metropolitan-gov/covid19, pull requests merged in 2022-10, with the labels that each got.

#7557 stylelint migrating to 14
  assets/monitoringItemsTableCommon.scss
  assets/variables.scss
  components/_shared/NoScript.vue
  components/_shared/SideNavigation.vue
  components/_shared/SideNavigation/LanguageSelector.vue
  components/_shared/StaticCard.vue
  components/index/CardsFeatured/ConfirmedCasesDetails/Table.vue
  components/index/CardsFeatured/InfectionSummary/Frame.vue
  components/index/CardsFeatured/InfectionSummary/Table/InfectionStatus.vue
  components/index/CardsFeatured/MedicalCareSummary/Table/MedicalSystem.vue
  components/index/CardsFeatured/MonitoringComment/CommentFrame.vue
  components/index/CardsFeatured/TestedNumber/Card.vue
  components/index/CardsMonitoring/MonitoringItemsOverview/Table/InfectionStatus.vue
  components/index/CardsMonitoring/MonitoringItemsOverview/Table/MedicalSystem.vue
  components/index/CardsMonitoring/UntrackedRate/Chart.vue
  components/index/CardsTab.vue
  components/index/SiteTopUpper/Consultation/StaticInfo.vue
  components/index/SiteTopUpper/StayingPopulation.vue
  components/index/SiteTopUpper/WhatsNew.vue
  components/index/_shared/DataView.vue
  components/index/_shared/DataView/Share.vue
  components/index/_shared/DateRangeSlider.vue
  layouts/default.vue
  layouts/error.vue
  layouts/print.vue
  package.json
  pages/accessibility-results.vue
  pages/contacts.vue
  stylelint.config.js
  yarn.lock
Labels: preview-deploy

#7562 static/dataディレクトリを削除
  static/data/.gitattributes
  static/data/130001_tokyo_covid19_7119_fever_consultation_center_calls.csv
  static/data/130001_tokyo_covid19_call_center.csv
  static/data/130001_tokyo_covid19_combined_telephone_advice_center.csv
  static/data/130001_tokyo_covid19_details_testing_positive_cases.csv
  static/data/130001_tokyo_covid19_patients_2020.csv
  static/data/130001_tokyo_covid19_patients_2021.csv
  static/data/130001_tokyo_covid19_patients_2022-1.csv
  static/data/130001_tokyo_covid19_patients_2022-2.csv
  static/data/130001_tokyo_covid19_patients_2022.csv
  static/data/130001_tokyo_covid19_patients_9e4b6290e76826a41c5e34ac575ec04f.csv
  static/data/130001_tokyo_covid19_patients_per_report_date.csv
  static/data/130001_tokyo_covid19_positive_cases_by_day_of_confirmation.csv
  static/data/130001_tokyo_covid19_positive_cases_by_day_of_symptom_onset.csv
  static/data/130001_tokyo_covid19_positive_cases_by_municipality.csv
  static/data/130001_tokyo_covid19_positivity_rate_in_testing.csv
  static/data/130001_tokyo_covid19_tests_conducted.csv
  static/data/130001_tokyo_covid19_tokyo_rule_for_emergency_medical_care.csv
Labels: ready-for-merge

#7577 サイドナビURL変更・サイトトップ文言修正
  components/_shared/SideNavigation.vue
  components/index/SiteTopUpper/Consultation.vue
Labels: ready-for-merge, officially-approved

#7596 病床使用率等と患者の発生状況等を統合
  assets/json/cardRoutesSettings.json
  components/index/CardsFeatured.vue
  components/index/CardsFeatured/InfectionSummary/Card.vue
  components/index/CardsFeatured/InfectionSummary/Table/MedicalSystem.vue
  components/index/CardsFeatured/MedicalCareSummary/Card.vue
  pages/cards/_card.vue
Labels: ready-for-merge, officially-approved, preview-deploy

#7600 検査陽性者の状況の整理改修
  components/index/CardsFeatured/ConfirmedCasesDetails/Card.vue
  components/index/CardsFeatured/ConfirmedCasesDetails/Table.vue
  libraries/auto_generated/data_converter/convertPositiveStatusSummary.ts
  libraries/repositories/PositiveStatusSummaryRepository.ts
  store/index.ts
  utils/formatConfirmedCases.ts
Labels: ready-for-merge, officially-approved, preview-deploy

#7610 モニタリング項目の整理改修
  components/index/CardsMonitoring/MonitoringItemsOverview/Card.vue
  components/index/CardsMonitoring/MonitoringItemsOverview/Table/InfectionStatus.vue
  components/index/CardsMonitoring/MonitoringItemsOverview/Table/MedicalSystem.vue
  components/index/CardsMonitoring/MonitoringItemsOverview/Table/ValueWithTranslatableUnit.vue
  store/index.ts
Labels: ready-for-merge, officially-approved, preview-deploy

#7606 「報告日別による陽性者数の推移」カードのボタンを削除・リンクテキストとリンク先を修正
  components/index/CardsFeatured/ConfirmedCasesNumber/Card.vue
Labels: ready-for-merge, officially-approved, preview-deploy

#7604 「年代別新規陽性者数」カードを追加
  assets/json/cardRoutesSettings.json
  components/_shared/CustomExpansionPanel.vue
  components/index/CardsFeatured.vue
  components/index/CardsFeatured/PositiveNumberByAge/Card.vue
  components/index/CardsFeatured/PositiveNumberByAge/Chart.vue
  components/index/_shared/DataView.vue
  components/index/_shared/DataView/ExpantionPanel.vue
  libraries/auto_generated/data_converter/convertPositiveByAgegroup.ts
  libraries/repositories/PositiveByAgegroupRepository.ts
  pages/cards/_card.vue
  store/index.ts
Labels: officially-approved, preview-deploy

#7613 カードのレイアウト調整
  assets/json/cardRoutesSettings.json
  components/index/CardsFeatured/ConfirmedCasesDetails/Table.vue
  components/index/CardsFeatured/PositiveNumberByAge/Card.vue
  components/index/CardsFeatured/PositiveNumberByAge/Chart.vue
  components/index/CardsMonitoring.vue
  components/index/CardsReference.vue
  components/index/CardsReference/UntrackedRate/Card.vue
  components/index/CardsReference/UntrackedRate/Chart.vue
  components/index/CardsReference/UntrackedRate/DataViewDataSetPanel.vue
  libraries/auto_generated/data_converter/convertMonitoringItems.ts
  libraries/auto_generated/data_converter/convertPositiveStatusSummary.ts
  pages/cards/_card.vue
Labels: ready-for-merge, officially-approved, release-schedule-available, preview-deploy

#7618 年代別新規陽性者数のオープンデータリンク先URL追加
  components/index/CardsFeatured/PositiveNumberByAge/Card.vue
Labels: ready-for-merge, officially-approved, preview-deploy
