Repository tokyo-metropolitan-gov/covid19, pull requests merged in 2023-02, with the labels that each got.

#7717 「YYYY年MM月DD日の状況」カードに注釈を追加
  components/index/CardsFeatured/InfectionSummary/Card.vue
Labels: ready-for-merge, officially-approved, preview-deploy

#7718 yarn lint:fixを実行
  app/router.scrollBehavior.js
  components/index/CardsFeatured.vue
  components/index/CardsMonitoring.vue
  components/index/CardsReference.vue
  components/index/_shared/DataView/Share.vue
  layouts/default.vue
  pages/cards/_card.vue
  utils/i18nUtils.ts
Labels: ready-for-merge, preview-deploy

#7742 「X月X日の状況」カードの一部注釈を削除
  components/index/CardsFeatured/InfectionSummary/Card.vue
Labels: ready-for-merge, officially-approved

#7740 オミクロン株対応ワクチンに関する情報をグラフに追加
  components/index/CardsFeatured/Vaccination/Card.vue
  components/index/CardsFeatured/Vaccination/Chart.vue
  libraries/auto_generated/data_converter/convertVaccinationCountWithOmicron.ts
  libraries/repositories/VaccinationCountWithOmicronRepository.ts
  store/index.ts
Labels: ready-for-merge, officially-approved
